### ISSUE TITLE
Ever Since Upgrade: TypeError: Cannot read property 'Store' of undefined

### ISSUE THREAD

**Issue by austencollins** [jdesboeufs/connect-mongo#101]
I upgraded connect-mongo today and my application keeps crashing due to the following error.  Can anyone contribute any advice on this issue?:

```
/Desktop/node/application/node_modules/connect-mongo/lib/connect-mongo.js:30
  var Store = connect.session.Store;
                             ^
TypeError: Cannot read property 'Store' of undefined
```

```
//express/mongo session storage
        app.use(express.session({
            secret: '90s8fa0s8fa',
            store: new mongoStore({
                url: config.db,
                collection: 'sessions'
            })
        }));
```

**Comment by rknell** [comment]
For any other suckers out there who are banging their head against this, also remember that you need to add session after you require connect-mongo:
``` javascript
var session = require('express-session');
var MongoStore = require('connect-mongo')(session);

```

This will cause the same error!

**Comment by phsstory** [comment]
@rknell Thank you.

I mistakenly used the docs example https://github.com/kcbanner/connect-mongo#re-use-a-mongoose-connection which dosn't use the require function call.

**Comment by Kikketer** [comment]
I assume this issue does not exist in the latest 0.8.2 version (which I got from NPM).  I'm getting this error when using Mongoose.

I have the session set up correctly per above.  I've tried both `store: new MongoStore({db: mongoose.connection.db})` and the `store: new MongoStore({mongooseConnection: mongoose.connection})` variety.

**Comment by rknell** [comment]
@Klkketer This isn't using mongoose, but if you are stuck and need to get on with it check out this working example from my seed project:

https://github.com/rknell/snappyapps-seed/blob/master/engine/lib/express.js

Super tested and totally working.

**Comment by Kikketer** [comment]
@rknell Not sure what you are pointing at with that link.  Looking around the source code of that project, the session:
````
app.use(session({
  secret: '1234890sdlkjfu02',
  resave: false,
  saveUninitialized: true
}));
````

I don't see any use of mongo or mongoose with the session config.  Did I miss something?

**Comment by paramsiddharth** [comment]
> @rknell Not sure what you are pointing at with that link. Looking around the source code of that project, the session:
> 
> ```
> app.use(session({
>   secret: '1234890sdlkjfu02',
>   resave: false,
>   saveUninitialized: true
> }));
> ```
> 
> I don't see any use of mongo or mongoose with the session config. Did I miss something?

Are you sure you didn't miss the `(session)` in `var MongoStore = require('connect-mongo')(session);`?

**Comment by jerevick83** [comment]
I advice you upgrade your package.json dependencies 

in your terminal, cd to your project root directory and enter the following:

`npm install -g npm-check-updates`

`ncu -u`

`npm updates`

`npm install`
