### ISSUE TITLE
Fails when given a complex mongodb uri

### ISSUE THREAD

**Issue by jasonsims** [jdesboeufs/connect-mongo#134]
On [connect-mongo.js#L46](https://github.com/kcbanner/connect-mongo/blob/master/lib/connect-mongo.js#L46), I think the config property `options.url` should be parsed with a library such as [mongo-uri](https://github.com/supershabam/mongo-uri) instead of using `url.parse`. If a complex mongo uri string is given which includes replica sets and various options this library will bomb when it tries to initialize the DB. 

```
mongodb://localhost:27017/testdb                            <-- Works out ok
mongodb://user:pass@localhost:27017,localhost:27018/testdb  <-- Breaks things
```

**Comment by umassthrower** [comment]
Good change, I had been using 0.4.2 with the call to validateDatabaseName commented out for this reason.
