### ISSUE TITLE
req.logout doesn't remove session in sessionStore with connect-mongo

### ISSUE THREAD

**Issue by snowdream** [jdesboeufs/connect-mongo#140]
I'm using passport-local. I have a logout method that calls req.logout to end the session. The problem is it doesn't clear req.session so connect saves a bogus session entry to mongowhen req.send is called:

Before logout:
1) {
    "_id" : "WQG-dceSqUwgwqWVOAOdjN11cLjLTsUb",
    "session" : "{\"cookie\":{\"originalMaxAge\":2592000000,\"expires\":\"2015-01-23T14:20:52.219Z\",\"httpOnly\":true,\"path\":\"/\"},\"passport\":{}}",
    "expires" : ISODate("2015-01-23T14:20:52.219Z")
}
After logout:
1) {
    "_id" : "WQG-dceSqUwgwqWVOAOdjN11cLjLTsUb",
    "session" : "{\"cookie\":{\"originalMaxAge\":2592000000,\"expires\":\"2015-01-23T14:20:52.219Z\",\"httpOnly\":true,\"path\":\"/\"},\"passport\":{}}",
    "expires" : ISODate("2015-01-23T14:20:52.219Z")
}

Is this something we're expected to take care of ourselves?

**Comment by paolodiprima** [comment]
Hello, answer
 jdesboeufs commented on 25 Dec 2014
is still valid in 2019 ?

**Comment by Sphinxs** [comment]
Another way to do this is:

```js
new Promise((resolve, reject) => {
    request.session.destroy((error) => {
      if (error) reject(error);

      response.clearCookie(process.env.SESSION_NAME);

      request.session = null;

      resolve(true);
    });
  });
```
