### ISSUE TITLE
I've been using connect-mongo(session) and I can login only at second time

### ISSUE THREAD

**Issue by efkan** [jdesboeufs/connect-mongo#145]
Hello,

I've been experiencing a strange issue :) I've been dealing with sessions with express.js. A whole day I've tried to solve my authentication issue but I couldn't. I cannot login at one time using MongoStore (connect-mongo).

_What should I do?_ :)

I think the reason is async Javascipt functions.

I can login with just one click using the below lines ( the codes don't have a MongoStore );

```
var MongoStore = require('connect-mongo')(session); 
app.use(require('cookie-parser')());
app.use(session({ 
secret: "mySecretKey",
    resave: true,
    saveUninitialized: true,
    cookie: { maxAge: 10 * 60 * 1000 },
}));
```

Bu if I try to use MongoStore as the below lines, **I have to try login more than one time** using my username and password.

```
app.use(require('cookie-parser')());
app.use(session({ 
secret: "mySecretKey",
    resave: true,
    saveUninitialized: true,
    cookie: { maxAge: 10 * 60 * 1000 },
    store: new MongoStore({
        url: mongoDBUrl
    }) 
}));
```

**Comment by pythonbabu** [comment]
Hey @efkan , iam not getting any proper guide or tutorial how to use connect-mongo with native mongodb driver, can you please share your code or give me a node js code written to demonstrate how to use connect-mongo , that prints out session stored and session deleted in the database when its corresponding actions takes place..!?!?

I could'nt even find how to use connect-mongo even in the stackoverflow. 
Have a look at this post : https://stackoverflow.com/questions/43929811/how-to-use-sessions-with-connect-mongo

**Comment by pythonbabu** [comment]
@efkan 
If possible please use a promise for the CRUD operations that take place in the connect-mongo module with a dbPromise attribute set to a promise function.

**Comment by efkan** [comment]
Hello @pythonbabu ,
Sorry for late. I cannot access my computer right now.
On Sunday or Monday I can share the related code. 
Which reminds me that I use Mongoose and provide Mongoose connection to connect-mongo.

Have a beautiful weekend!

**Comment by efkan** [comment]
@pythonbabu I've taken a look at your SO question.

I use passportjs to authenticate the user and it exposes `req.user` object.

And also I query MongoDB for avatar data at every request. Of course this is not one of the best practices. 

My code the same as directed in [readme](https://github.com/jdesboeufs/connect-mongo#re-use-a-mongoose-connection) file:

```
var session = require('express-session') // to generate session object
var MongoStore = require('connect-mongo')(session) // to store session object on the MongoDB
...

app.use(session({
  secret: config.sessionSecretKey,
  resave: true,
  saveUninitialized: true,
  cookie: { maxAge: 19 * 60000 }, // store for 19 minutes
  store: new MongoStore({
    mongooseConnection: mongoose.connection
  })
}))
```

Good luck..

**Comment by pythonbabu** [comment]
thank you very much for your help sir.

**Comment by Mohamed-kamel91** [comment]
@efkan so the only way to connect express session to mongo store is through a mongoose connection ? 
i can't seem to find anyone talking about or give a proper answer on how to connect express session to a native mongodb store, reuse an exisiting native mongodb client is a big headache as it always return this error: 
**Assertion failed: You must provide either mongoUrl|clientPromise|client in options
Error: Cannot init client. Please provide correct options**
