### ISSUE TITLE
Database replacement without native components

### ISSUE THREAD

**Issue by Phoscur** [jdesboeufs/connect-mongo#229]
Hiho,
Since #179 was closed, I'm opening a new topic to discuss which MongoDB alternative could and should be supported as a non-native alternative.
I haven't had time for more [TingoDB](https://github.com/sergeyksv/tingodb) experiments, but I also just discovered [NeDB](https://github.com/louischatriot/nedb).

Usecases:
- running a deployment on android
- running a deployment on a raspberrypi
  ..

**Comment by jdesboeufs** [comment]
Feel free to add NeDB or TingoDB support :)
I close this issue for now.
