### ISSUE TITLE
How to import connect-mongo (session) in ES6?

### ISSUE THREAD

**Issue by lautiamkok** [jdesboeufs/connect-mongo#235]
In pre-ES6, this is how I import `connect-mongo` (session):

```
`var MongoStore = require("connect-mongo")(session);`
```

But how can I import it in ES6?

```
 import MongoStore from 'connect-mongo';
 let monStore = MongoStore(session);

```

Error:

``````
```
const Store = connect.Store || connect.session.Store;
                                                  ^
TypeError: Cannot read property 'Store' of undefined
``````

```
Any ideas?
```

**Comment by conor909** [comment]
I'm using the `require` method:
`var MongoStore = require("connect-mongo")(app);`

I get the same error `TypeError: Cannot read property 'Store' of undefined`.  It looks like a bug the library?

**Comment by jdesboeufs** [comment]
You can try something like this:

```js
import connectMongo from 'connect-mongo';
import session from 'express-session';

const MongoStore = connectMongo(session);
```
Le jeu. 8 sept. 2016 à 23:16, Conor McGrath <notifications@github.com> a
écrit :

**Comment by jdesboeufs** [comment]
You can try something like this:

```js
import connectMongo from 'connect-mongo';
import session from 'express-session';

const MongoStore = connectMongo(session);
```

**Comment by conor909** [comment]
Thanks!  I read a tutorial wrong.  This was also helpful https://github.com/jdesboeufs/connect-mongo#express-or-connect-integration
