### ISSUE TITLE
How can I remove the specified session from Mongodb 

### ISSUE THREAD

**Issue by Arvin333** [jdesboeufs/connect-mongo#236]
I connet to the mongodb and get the MongoStore instance like this:
```
let MongoInstance = new MongoStore({
					  url:'mongodb://localhost/react',
					  autoRemove: 'disabled'
				   })
```
and now I wanna remove the specified session with the MongoStore instance method '**destroy**'
```
app.all("/destroy",(req,res)=>{
	MongoInstance.destroy(req.session.id)
})
```
when i visit destroy page,there is no error. However, the session is mongodb has not been removed yet!
the database connection is ok and no syntax error.
can you help me out?

**Comment by vko-online** [comment]
What's the solution @Arvin333 ?
