### ISSUE TITLE
Overwriting the Existing record

### ISSUE THREAD

**Issue by abhiCR7** [jdesboeufs/connect-mongo#240]
I have 2 parallel requests(R1 and R2) . Both of them write some data in the record(record D1). So it's kind of race condition. If R1 writes something to the D1 and it gets persisted, then R2 writes something to the in-memory copy of D1 and saves it which results in loss of data written by R1(vice versa). 
Is there anyway where we can write the only diff in the record instead of overwriting the whole record

**Comment by goodfella1408** [comment]
What is the recommended way of handling this .Ideally R2 should fail because it is trying to update an old version of the document
