### ISSUE TITLE
using 'connect-mongo/es5' options.db.listCollections is undefined

### ISSUE THREAD

**Issue by svassr** [jdesboeufs/connect-mongo#241]
I received the error `Connection strategy not found` (from **_node_modules/connect-mongo/src-es5/index.js:127:23_**) and noticed `options.db` is ok but `options.db.listCollections` is undefined.

I'm using 
- mongo 2.6.12
- mongo npm driver mongodb@1.4.12
- express@3.4.3 
- connect-mongo@1.3.2

Here is the code instantiate and use MongoStore 

```
var MongoStore = require('connect-mongo/es5')(expressConnect), 
    sessionStore = new MongoStore({
        db: db,
        w: 1,
        collection: 'sessions'
    }),
    sessionMiddleware = express.session({
        secret: 'XXXXX',
        store: sessionStore
    }),
    passportMiddleware = passport.initialize();

// Authentication services.
app.get(
    '/api/v1.X/auth',
    sessionMiddleware,
    passportMiddleware,
    authService.onAuth
);
```

**Comment by jdesboeufs** [comment]
Versions not supported anymore.
Please upgrade to 2.0.0!
