### ISSUE TITLE
Support async serialize and unserialize?

### ISSUE THREAD

**Issue by breeswish** [jdesboeufs/connect-mongo#243]
We want to store only uid in the session and populate the user object every time session is read from the database (so that we only maintain exactly one copy of `User`).

To avoid unnecessary modifications, we plan to use `serialize` and `unserialize` hook (in `serialize`, replace the user object with user id; in `unserialize`, replace user id with user object). However currently `unserialize` is sync, which means we cannot perform a query inside `unserialize`.

**Comment by jdesboeufs** [comment]
Why not use a middleware for that? Or passport?

Serialize/unserialize is related to session transformation.

**Comment by gkostov** [comment]
Hi,

I've been looking to achieve the same, but even if I see how to add some middleware to populate the `User` object after the session's been loaded, I can't see how to do the reverse (replace the object with the user's id) before the session gets to be saved. `express-session` appears to be saving the session when `res.end()` gets called and I see no official way to hook into that.

I can likely hack it in somehow but was wondering if there is some proper way to do that?

Thanks
