### ISSUE TITLE
Syntax Error: unexpected token =>

### ISSUE THREAD

**Issue by softiran** [jdesboeufs/connect-mongo#245]
Hi I have the following error

node_modules/connect-mongo/src/index.js:29
            unserialize: options.unserialize || (x => x),
                                                   ^^
node@v3.3.1
express@4.14.0 
mongoose@4.6.5 
mongodb@2.2.11

**Comment by jdesboeufs** [comment]
`node@3.3.1` doesn't support ES6 syntax.

Please read:
https://github.com/jdesboeufs/connect-mongo/blob/master/README.md#old-nodejs-versions-compatibility
Le lun. 31 oct. 2016 à 08:35, Alireza Ghaffari <notifications@github.com> a
écrit :
