### ISSUE TITLE
exception at require 

### ISSUE THREAD

**Issue by amigo421** [jdesboeufs/connect-mongo#251]
I'm using this code

```
const MongoStore = require('connect-mongo')(express);
app.use(session({
  secret: 'my secret',
  resave: false,
  saveUninitialized: false,
  store: new MongoStore({
        url: 'mongodb://test:test@1.1.1.1:27017/my-secret?authSource=admins&w=1'
    })
}))
```

but when I'm trying to run , I'm getting an exception:
![image](https://cloud.githubusercontent.com/assets/3259933/21486379/b36d8216-cbc4-11e6-9efe-b07a8c08180b.png)

![image](https://cloud.githubusercontent.com/assets/3259933/21486392/d61b455a-cbc4-11e6-8e33-fc68b8759e2d.png)

I'm newbie, and possibly that is not a bug but my incorrect usage, please comment

**Comment by MichaelBeier** [comment]
in case you haven't figured out a solution yet. Try passing express-session instead of express on require. I had a similiar issue.
