### ISSUE TITLE
Example Usage opens new db connection on each page load

### ISSUE THREAD

**Issue by ragulka** [jdesboeufs/connect-mongo#252]
There is a major issue with the example usage - we just encountered it in a production app and it stabbed us in the back real bad.

```javascript
app.use(session({
    secret: 'foo',
    store: new MongoStore(options)
}));
```

The above code creates a __new DB connection on every single page load__, and keeps that connection open, __without ever closing it__. At least that's the case when passing in a db URL (I haven't tested with other options).

On a site that receives even a moderate amount of traffic, this can quickly create hundreds and thousands of db connections. Having thousands of open connections will increase app memory usage (it's basically a memory leak) and it can affect db queries (lag, etc). We for example experienced issues where some simple DB queries never returned a result (timed out), or took 2-3 minutes to complete.

I know that there are examples on how to re-use a mongoose connection, but I think the other examples should also always encourage users to create a single connection. The above could simply be rewritten as:

```javascript
var sessionStore = new MongoStore(options);
app.use(session({
    secret: 'foo',
    store: sessionStore
}));
```

It's a really small change, but it has a huge effect. In fact, we made the exact same change in our production app and saw open connections drop from 1500 to 40. That's massive!

I would suggest to rewrite all the examples so that new users who do not spot the flaw in the current version, would not get caught off guard by this.

**Comment by jdesboeufs** [comment]
There is no difference between the two implementations. You just assign your instance reference to a scoped variable.

**Comment by ragulka** [comment]
> There is no difference between the two implementations. You just assign your instance reference to a scoped variable.

You'd assume that's true. However, if you pass in the db url (not an already existing DB connection), a new db connection is opened every time. This is evidenced by my experience in making this small change in our production app. We're down from 1500 db connections to 40, and a leaky memory to a stable memory usage.

**Comment by jdesboeufs** [comment]
Very difficult to admit :/
You must have an unattended side-effect.

Can you describe your environment?
