### ISSUE TITLE
Is there any plans on implementing the .all function?

### ISSUE THREAD

**Issue by djiordhan** [jdesboeufs/connect-mongo#257]
The [express-session](https://github.com/expressjs/session/blob/master/session/memory.js#L58) MemoryStore and [Redis](https://github.com/tj/connect-redis/blob/master/lib/connect-redis.js#L281) implements this, im just thinking this could be implemented here too.

We want to limit the concurrent sessions per user. I could just query all sessions from sessions collection but Im thinking if we could do it by implementing the .all function. Thanks

I already added this under my node_module and this works.

`
all(callback) {
 return this.collectionReady()
                    .then(collection => collection.findAsync({
                        $or: [
                            { expires: { $exists: false } },
                            { expires: { $gt: new Date() } },
                        ]
                    }))
                    .asCallback(callback);
        }
`

**Comment by chuangl** [comment]
Thank you very much. I am a newcomer to this. I have 2 problems when I modify this.One is the 'findAsync is not defined', solution: I add find string in setCollection like this ['find'...].forEach(method...;
The other is findAsync return mongodb cursor in my situation, my solution is use cursor.toArray(),then return a new Array.
Any suggestion for me,Thanks

**Comment by IRETD** [comment]
Yes, it's a really necessary feature!
