### ISSUE TITLE
Re-use a native MongoDB driver connection (or a promise)

### ISSUE THREAD

**Issue by jakubrpawlowski** [jdesboeufs/connect-mongo#261]
I am unable to create the following: "Re-use a native MongoDB driver connection (or a promise)"

It always returns the error: "Connection strategy not found", because in normal Express structure all app.use go before mongoclient.connect (which has app.listen in it).
```
 var db = {};
 app.use(expresssession({
   secret: 'xxx',
   resave: false,
   saveUninitialized: false,
   store: new mongostore({
      db: db,
      collection: 'sessions',
      ttl: 24 * 60 * 60
   })
}));

mongoclient.connect(mongourl, (error, database) => {
  if (error) return console.log(error);`

  db = database;
  
  app.listen(port, function(){
    console.log('Listening on port: ' + port);
  });
});
```

The only way I know how to make connect-mongo work with MongoDB driver is by using url instead of db:

```
store: new mongostore({
    url: mongourl,
    collection: 'sessions',
    ttl: 24 * 60 * 60
  })
```

but this from all my testing ends up making hundreds of db connections as described in open issue: https://github.com/jdesboeufs/connect-mongo/issues/252

**Comment by jakubrpawlowski** [comment]
Temporary fix is to place all app.use middle ware inside connect callback:
```
mongoclient.connect(mongourl, (error, database) => {
   if (error) return console.log(error);`

   db = database;

   app.use...
   app.use...
   app.listen...
}
```
But I don't think that this is intended structure for production.

**Comment by dangkhoa12pfiev3** [comment]
Did you resolve this problem @jakubrpawlowski  ? I have same issue. Thank you

**Comment by jakubrpawlowski** [comment]
The only advice I can give you is to use [mongoose](https://www.npmjs.com/package/mongoose) instead of [mongodb](https://www.npmjs.com/package/mongodb). It works with connect-mongo without any issues mentioned above. If you're not sure how to set it up you can [watch this video guide](https://www.youtube.com/watch?v=56TizEw2LgI&list=PL55RiY5tL51rajp7Xr_zk-fCFtzdlGKUp).
Good luck!

**Comment by saltire** [comment]
You could probably put your `app.use()` call inside the callback from `MongoClient.connect()`.

You can also use the promise returned from `MongoClient.connect()` and pass it to the `MongoStore` constructor:

```
const dbPromise = mongoclient.connect(mongourl);

app.use(expresssession({
  secret: 'xxx',
  resave: false,
  saveUninitialized: false,
  store: new mongostore({
    dbPromise,
    collection: 'sessions',
    ttl: 24 * 60 * 60
  })
));

dbPromise.then(() => {
  app.listen(port, () => {
    console.log('Listening on port: ' + port);
  });
});
```

**Comment by MiKr13** [comment]
I am having the same issue.
Express.js file:

    module.exports= function(db) {
    var app= express();

    if(process.env.NODE_ENV=== 'development') {
        app.use(morgan('dev'));
    } else if(process.env.NOVE_ENV=== 'production') {
        app.use(compress());
    }

    var mongoStore= new MongoStore({
        db: db
    });
    
    app.use(session({
        saveUninitialized: true,
        resave: true,
        secret: config.sessionSecret,
        store: mongoStore
    }));
    return server;
    };

Server.js file:

    var mongoose= require('./config/mongoose.js'),
    express= require('./config/express.js'),
    var db= mongoose();
    var app= express(db);

    app.listen(3001);

    module.exports= app;

mongoose.js file:

    var config= require('./config'),
    mongoose= require('mongoose');

    module.exports= function() {
    var db= mongoose.connect(config.db, function(err) {
        if(err) console.log(err);
        else console.log('DB success');
    });

    require('../app/models/user.server.model.js');
    require('../app/models/article.server.model.js');

    return db;
    };

Error: Connection strategy not found

**Comment by saltire** [comment]
@MiKr13 Looks like you're passing the return value of `mongoose.connect()` as `db` to the `MongoStore` constructor, but `mongoose.connect()` returns a `Promise`. Similar to above, either instantiate the store inside of a callback from the Mongoose connection, or pass your `db` as `dbPromise` instead:

```
var mongoStore = new MongoStore({
    dbPromise: db
});
```
