### ISSUE TITLE
Mongoose 4.11+

### ISSUE THREAD

**Issue by michelem09** [jdesboeufs/connect-mongo#264]
Probably 4.11 of Mongoose breaks connect-mongo I always receive:

> Error: Connection strategy not found

Please look at this https://github.com/Automattic/mongoose/issues/5399

**Comment by agoldis** [comment]
mongoose 4.11+ shows deprecation warning when using `open`, which causes users to switch to `useMongoClient` option (https://github.com/Automattic/mongoose/issues/5304)

That causes the returned value to be a Promise, and instead of `mongooseConnection`. `dbPromise` option should be used:
```javascript
const connectionPromise = mongoose.createConnection(uri, { useMongoClient: true });
const MongoStore = require('connect-mongo')(session);
    app.use(session({
      resave: false,
      saveUninitialized: false,
      secret: 'xxx',
      ttl: 14 * 24 * 60 * 60, // 14 days
      store: new MongoStore({ dbPromise: connectionPromise })
}));

**Comment by nanom1t** [comment]
@agoldis Thanks for your example, but it does not work for me. Here is my app.js:
```
...
var express = require('express');
var session = require('express-session');
var MongoStore = require('connect-mongo')(session);
var mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
var mongoosePromise = mongoose.createConnection('mongodb://user:password@127.0.0.1:27017/MyDB', { useMongoClient: true });
....
app.use(session({
    name: configs.SESSIONS_ID,
    secret: configs.SESSIONS_SECRET,
    store: new MongoStore({ dbPromise: mongoosePromise, ttl: configs.SESSIONS_TTL, autoRemove: 'native'}),
    saveUninitialized: true,
    resave: false,
    proxy: true
}));
```
In this case my app is loading very long period of time (more than 1 minute) and then I get 502 gateway timeout. However, everything works good when I'm using deprecated connect method, but I get `DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0`:
```
var mongoose = require('mongoose').connect('mongodb://user:password@127.0.0.1:27017/MyDB');
...
app.use(session({
    name: configs.SESSIONS_ID,
    secret: configs.SESSIONS_SECRET,
    store: new MongoStore({ mongooseConnection: mongoose.connection, ttl: configs.SESSIONS_TTL, autoRemove: 'native'}),
    saveUninitialized: true,
    resave: false,
    proxy: true
}));
 
Could you please help with this issue?

Thanks

**Comment by ilarioengler** [comment]
@nanom1t 

> However, everything works good when I'm using deprecated connect method, but I get DeprecationWarning:open()is deprecated in mongoose >= 4.11.0:

mongoose.connect() method is not deprecated.

Open connection like this..
`let conn = mongoose.connect(uri, { useMongoClient: true });`

Specify store like this..
`app.use(session({ store: new MongoStore({ mongooseConnection: mongoose.connection })}));`

**Comment by Spown** [comment]
and how do I specify it if I use ``mongoose.createConnection``? because right now (after switching to mongoose 4.12.2 and { useMongoClient: true }) I get:
![](https://drive.google.com/uc?id=0B-OJBofmehO3Rko5ZmM0c2pYWFU)

I do something like this:
```js
        mongooseConnection = mongoose.createConnection(setts.db.connectionString, connOpts);
...
        mongooseConnection
        .on('error', function(er) {
            bootMongo.reject(new Error(`failed to connect to DB! ${er}`));
        })
        .on('connected', function() {
            dlog( 'mongooseConnection connected' );
            bootMongo.resolve({connection: this});
        })
        ;
...
      bootMongo.promise.then(function (mongo) { //it's a Q promise
...
        mongo && app.use(session({
            'secret': XXXX,
            'store': new MongoStore({ 'mongooseConnection': mongooseConnection }),
            'cookie': { 'maxAge': 24 * 60 * 60000 },
            'resave': true,
            'saveUninitialized': true
        }));
```
``mongooseConnection`` here is a ``NativeConnection`` and it is also ``mongooseConnection === mongo.connection`` which is btw not exactly the same thing as the ``NativeConnection`` created without ``useMongoClient`` (see [mongoose#5714](/Automattic/mongoose/issues/5714))
