### ISSUE TITLE
ensureIndex is deprecated in Mongoose >= 4.12.0

### ISSUE THREAD

**Issue by efkan** [jdesboeufs/connect-mongo#268]
When my app starting up, I get this warning:

`DeprecationWarning: `ensureIndex()` is deprecated in Mongoose >= 4.12.0, use `createIndex()` instead`

**Comment by jjtortosa** [comment]
+1

**Comment by X-XXX** [comment]
+1

**Comment by ivancsicsmarkus** [comment]
+1

**Comment by AdoneZ** [comment]
+1

**Comment by jdesboeufs** [comment]
OK working on it. We already have two PR but it needs further investigation for prior-3.0 MongoDB versions.

**Comment by jdesboeufs** [comment]
Published `2.0.0`
