### ISSUE TITLE
require('mongodb').pure() is not a function

### ISSUE THREAD

**Issue by PedramMarandi** [jdesboeufs/connect-mongo#273]
Hi folks 
I've been struggling with this error. I didn't find any change related to pure function and it still passing the tests on mongodb master branch, I don't know what problem exactly is.

> var BSON = require('mongodb').pure().BSON;
>                               ^
> 
> TypeError: require(...).pure is not a function
>     at Object.<anonymous> (/Users/PedramMarandi/projects/twitter/node_modules/mongo-connect/lib/mongo-connect.js:3:31)
>     at Module._compile (module.js:635:30)
>     at Module._extensions..js (module.js:646:10)
>     at Object.require.extensions.(anonymous function) [as .js] (/Users/PedramMarandi/projects/twitter/node_modules/babel-register/lib/node.js:152:7)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/Users/PedramMarandi/projects/twitter/app/lib/Session/index.js:2:1)
>     at Module._compile (module.js:635:30)
>     at loader (/Users/PedramMarandi/projects/twitter/node_modules/babel-register/lib/node.js:144:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/Users/PedramMarandi/projects/twitter/node_modules/babel-register/lib/node.js:154:7)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)

Versions 
Node -> v8.9.1
"mongo-connect": "0.0.6"
"mongodb": "^2.2.33"

**Comment by PedramMarandi** [comment]
My stupid mistake, it's solved, guys.

**Comment by AbdAlhamidZobi** [comment]
just because maybe someone else falls this trap, you probably have installed `mongo-connect` not ***`connect-mongo`***

**Comment by Dev-Addict** [comment]
I'm Stupid
