### ISSUE TITLE
Writing to the 'sessions' collection

### ISSUE THREAD

**Issue by alexerhardt** [jdesboeufs/connect-mongo#274]
I am trying to write to the default 'sessions' collection created by connect-mongo, but for some reason I can't.

[Here's a more detailed look at the issue.](https://stackoverflow.com/questions/47722432/connect-mongo-why-cant-i-write-to-the-sessions-collection)

Any help would be appreciated - thanks.

**Comment by gjvpaet** [comment]
@alexerhardt  Any leads about this? I also want to write data to the sessions collections but I'm not sure exactly or is it possible to do.
