### ISSUE TITLE
with express-session, req.session.destroy invoke error.

### ISSUE THREAD

**Issue by baefoo004** [jdesboeufs/connect-mongo#277]
node version: 8.5.0
------- package.json --------
"connect-mongo": "^2.0.0",
"express": "~4.15.5",
"mongoose": "^5.0.0-rc1",
"express-session": "^1.15.6"

---------------------------------------------------------------

when i use mongo store and re-use mongoose connection, like below,

var session = require('express-session');
var MongoStore = require('connect-mongo')(session);

var db = mongoose.connect(config.MONGODB_URI);

app.use(session({
    name: '__usb',
    secret: config.SESSION_SECRET,
    resave: false,
    saveUninitialized: false,
    cookie: {
        maxAge: config.SESSION_TIMEOUT
    },
    store: new MongoStore({ mongooseConnection: db })
  }));

and if i call req.session.destroy(callback) the error is occured.

error message : 
TypeError: Cannot convert undefined or null to object
    at Function.assign (\<anonymous\>)
    at executeOperation (<my_directory>\node_modules\mongoose\node_modules\mongodb\lib\utils.js:386:14)
    at Collection.remove (<my_directory>\node_modules\mongoose\node_modules\mongodb\lib\collection.js:1232:10)
    at withCallback.collectionReady.then.collection (<my_directory>\node_modules\connect-mongo\src\index.js:293:48)
    at \<anonymous\>

so i changed from "store: new MongoStore({ mongooseConnection: db })" to "store: new MongoStore({ url: config.MONGODB_URI })" and then the error disappear.

**Comment by jdesboeufs** [comment]
Hi,

It seems mongoose 5 will not be compatible out-of-the-box.
We need to investigate.

**Comment by MongoExpUser** [comment]
I encountered the same problem when I upgraded to Mongoose 5.0.0.

**Comment by FourCourtJester** [comment]
Hi,

I've been banging my head against the wall that is this bug today. I connect using my db.connection(), and there were no issues in the upgrade to 5.0.0, until I deployed to my Docker. Then I get the same error baefoo004 whenever I tried to destroy the session.

Cheers

**Comment by alanosman** [comment]
We had the same error today when we upgraded our mongo modules because we had upgraded to connect-mongo 2.0.1.

`session.destroy` fails with the error:

```
TypeError: Cannot convert undefined or null to object
    at executeOperation (/mnt/d/elastc-app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:38
6:14)
    at Collection.remove (/mnt/d/elastc-app/node_modules/mongoose/node_modules/mongodb/lib/collection
.js:1239:10)
    at withCallback.collectionReady.then.collection (/mnt/d/elastc-app/node_modules/connect-mongo/src
/index.js:297:48)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

We downgraded to 1.3.2 - would love to see this fixed.  Thanks.

**Comment by FourCourtJester** [comment]
Unless updated by author, the fix proposed by baefoo004 does indeed fix the issue by adjusting the way we connect. Instead of re-using a connection, just connect using your mongo URL

> so i changed from "store: new MongoStore({ mongooseConnection: db })" to "store: new MongoStore({ url: config.MONGODB_URI })" and then the error disappear.

**Comment by MongoExpUser** [comment]
I solved this problem by simply switching from **"connect-mongo"** to **"express-mongoose-store"** for my mongoStore

Note: express-mongoose-store is compatible with "mongoose", hence, this option works WITH (AND ACCEPTS) current or existing "mongoose" connection
    
**Find below my sample connection codes:**
1) install "express-mongoose-store"
sudo npm i express-mongoose-store   

2) codes in app.js
const session    = require('express-session');
const mongoose   = require('mongoose');   
const mongoStore = require('express-mongoose-store')(session, mongoose);

mongoose.connect(uri, connectionOptions, function(err) { });   //mongoose connection or existing mongoose connection       
const uuidV4     = require('uuid/v4');                         //generates cryptographically strong secret with UUID-v4     
const oneHour    = 60*60*1000; 
const store      = new mongoStore({mongooseConnection: mongoose.connection,  collection : "collectionName"});

app.use(session(
{
   secret            : uuidV4(), 
   cookie            : {maxAge: oneHour, secure: true}, 
   store             : store, 
   rolling           : false, 
   saveUninitialized : false, 
   resave            : false 
}));
       
 Also check: https://github.com/battlejj/express-mongoose-store

**Comment by earendillo** [comment]
@MongoExpUser it works, I simply installed and changed const mongoStore according to your post, any other reconfiguration was not necessary.

**Comment by alanosman** [comment]
I tried the mongostore solution and it worked, but we had issues with it elsewhere (can't recall exactly) and had to revert back to connect-mongo.  It would be great if the latest version of connect-mongo could be fixed of the authors gave us some other work-around.

Thanks.

**Comment by thatkyledude** [comment]
I had been running into this problem, and it looks like this is not Mongoose's fault, but all of us MongoDB 3.6 users. I dug through the source a bit and played around, and in the **destroy** function of the **MongoStore** class, the function property called on the collection is still **remove**, where MongoDB 3.6 would use **deleteOne**.

https://github.com/jdesboeufs/connect-mongo/blob/d395dc337d034e2312755b462c7df11d7905be97/src/index.js#L295

As soon as I change
`.then(collection => collection.remove({_id: this.computeStorageId(sid)}))`
to
`.then(collection => collection.deleteOne({_id: this.computeStorageId(sid)}))`
my site can finally log my out and says a cheerful "Goodbye!", instead of... well... we all know what the other one says. I'm not sure how I'd go about making this support 3.4 and 3.6, I've spent too many hours already looking at this, but if I come up with something good, I'll actually learn how Github works and make a pull request or something. =P

MongoDB 3.4 https://docs.mongodb.com/v3.0/tutorial/remove-documents/
MongoDB 3.6 https://docs.mongodb.com/manual/tutorial/remove-documents/
