### ISSUE TITLE
Can I store the session in the database together with the ip address?

### ISSUE THREAD

**Issue by morteryler** [jdesboeufs/connect-mongo#290]
How do I record the IP address of a visitor each time a new session is issued to him? I do not need this in order to protect the site from hackers.

**Comment by kounelios13** [comment]
Beware of the GDPR

**Comment by mingchuno** [comment]
despite the security and privacy issues, you can do like this:

```
// in some middleware
if (!req.session.ipAddress) {
  req.session.ipAddress = req.headers['x-forwarded-for'] || req.connection.remoteAddress
}
```

and remember to enable trust proxy

```
app.enable('trust proxy')
```
