### ISSUE TITLE
Way to disable session expiration date refreshing?!

### ISSUE THREAD

**Issue by leoyli** [jdesboeufs/connect-mongo#293]
Hi,

I've noticed inside the doc:

> Note: Each time an user interacts with the server, its session expiration date is refreshed.

Is anyway to disable this behaviour?  The reason is I'm developing a isomorphic React app.  In the server side rendering, I verify and store the JSON Web Token into the user session.  I want to align the expiration time with the token, cookie and the db-stored session, where so that TTL can be properly triggered once the token have been expired.

So far I'm only being able to set `roller: false` so that cookie is going to be destroyed by the browser, but I may have to wait extra time if the user triggering server-side-rendering and extending the session stored in the database....

Thanks!

**Comment by mingchuno** [comment]
@leoyli Have you tried
```
resave: false,
saveUninitialized: false,
```
? If it doesn't work, then I think there is no way to disable the behavior unless you contact the upstream https://github.com/expressjs/session
