### ISSUE TITLE
transformId() should allow asynchronous computations

### ISSUE THREAD

**Issue by nikwen** [jdesboeufs/connect-mongo#294]
I use `transformId()` to apply a cryptographic hash to the session id, which is very cpu-heavy and should be done asynchronously. It would be great if instead of the value itself `transformId()` could also return a Promise with the generated value.

I have implemented this in my fork as https://github.com/nikwen/connect-mongo/commit/18f01604fad6e7509da20a8557a3b78464ef11ec, but the implementation uses async/await, so it would break compatibility for Node versions <8.

**Comment by nikwen** [comment]
Update: I don't like force pushing to the master branch, so rebased versions of my patches will from now on be available in branches called `v2.x.x-modified`.

For v2.0.3 that is https://github.com/nikwen/connect-mongo/tree/v2.0.3-modified.

**Comment by mingchuno** [comment]
@nikwen Hi, may I ask what is the purpose of hashing the original sessionId? Since the default `genid` is just some random string and already sign by the secret you must provide? 

https://github.com/expressjs/session#genid

**Comment by nikwen** [comment]
@mingchuno One could indeed argue whether it is really needed.

Hashing the sessionId, however, makes it considerably harder to hijack user sessions for attackers with read (not write!) access to the database, thus preventing the modification of documents or, if applicable, the retrieval or modification of data from other storage services (e.g. Amazon S3).

Notice that read access to the database _is_ needed here, but it can be useful for limiting damage if attackers manage to obtain read access to the database (this might even happen through a bug in an application, similar to SQL injection) or if a malicious employee only has read access to the database or certain parts of it.

Here's a link to a corresponding Drupal feature request: https://www.drupal.org/project/drupal/issues/2164025

Please correct me if I'm missing something, especially with regard to the signing.

**Comment by jas-** [comment]
@nikwen why not create a pr to use `crypto.genRandomBytes()` along with a hash? Seems much more logical if you are worried about session prediction for use in a replay attack.

**Comment by mingchuno** [comment]
#314 related?

**Comment by jas-** [comment]
@mingchuno no, not related. The uniqueness of the session id coupled with the probability of a value being used more than once is a separate issue than providing the security of session data

**Comment by nikwen** [comment]
@jas- I abandoned the project that I was using `connect-mongo` in and do currently not have enough time to look into your suggestions. Feel free to apply a fix which you think does the job properly. :wink:

**Comment by jas-** [comment]
@nikwen thanks for the update, however @mingchuno is the maintainer. I just commented in on an issue that doesn't apply to the `connect-mongo` session store, and is more suitably implemented using existing API methods in `express`.

**Comment by nikwen** [comment]
@jas- Thank you for trying to help a stranger on the internet. :+1:

**Comment by mingchuno** [comment]
Okay, so I will close the issue at the moment.
