### ISSUE TITLE
DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead

### ISSUE THREAD

**Issue by AdelShokry** [jdesboeufs/connect-mongo#297]
i got this warning 
DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead 
with "mongoose": "^5.2.10",

**Comment by Avcajaraville** [comment]
Same here. Hope they update the module :)

**Comment by n0bit** [comment]
[Connect-mongodb-session](https://www.npmjs.com/package/connect-mongodb-session) is pretty much a drop-in replacement for connect-mongo. It will remove the deprecation warning, plus, it is maintained by the MongoDB team.
