### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by wootwoot1234** [jdesboeufs/connect-mongo#298]
Hey Guys,

I've been using this project for a while but it's no longer working with the latest mongoose version 5.2.14.  I'm getting the feeling that this is no longer being maintained which would be sad because it's such a great tool.

I really hope the answer is yes, it's still maintained.  :)

Best,
Tom

**Comment by wootwoot1234** [comment]
@jdesboeufs ?

**Comment by jdesboeufs** [comment]
I'm too busy at the moment but I'm okay to promote more maintainers.

**Comment by wootwoot1234** [comment]
@jdesboeufs This is not my wheelhouse but maybe some of the people posting pull requests would be interested?

**Comment by Avcajaraville** [comment]
@jdesboeufs & @wootwoot1234  Im also very busy, but I would like to at least update it to support mongoose 5.2.14

Will do a PR soon :)

Thanks !

**Comment by wootwoot1234** [comment]
@Avcajaraville Thanks!

**Comment by Avcajaraville** [comment]
@wootwoot1234 yeah... about that ... 😂 @jdesboeufs Im not able to follow the tests cases, so I dont think I will have that PR soon enough...  Code style, lack of comments and too few time for it, makes me drop this PR at this moment.

@jdesboeufs hopefully you maybe can help at some point, as you already know the code. :)

Good job anyways and really looking forward to use this package once its updated again :)

**Comment by jdesboeufs** [comment]
The tests cases are a legacy from the previous maintainer and creator of this lib (kcbanner).
I've never found the time to rewrite/migrate them.

**Comment by wootwoot1234** [comment]
Thanks for the update!  :)

**Comment by mingchuno** [comment]
Hi all, I have forked this repo and upgraded the mongoose to 5.x some time ago but have no time to make a formal PR yet. I shall be able to make a PR some time later...

**Comment by wootwoot1234** [comment]
@mingchuno, wasn't this project just updated a month ago?  

https://www.npmjs.com/package/connect-mongo

**Comment by mingchuno** [comment]
Hi @wootwoot1234, I have created a PR to support mongoose 5.x and mongodb driver 3.x #311 . But @jdesboeufs seems not around... I am okey to become maintainer

**Comment by jdesboeufs** [comment]
@mingchuno Thank you for your PR and welcome! :)
