### ISSUE TITLE
DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.

### ISSUE THREAD

**Issue by KSH-code** [jdesboeufs/connect-mongo#300]
i got this warning
DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
with "mongoose": "^5.2.15",

**Comment by Igor-Lopes** [comment]
Any updates on this issue and PR ?

**Comment by alanosman** [comment]
Yup - we are seeing this too.
