### ISSUE TITLE
When using autoRemove: 'interval' expired sessions are removed only once after the first interval

### ISSUE THREAD

**Issue by jlampise** [jdesboeufs/connect-mongo#304]
I examined this a bit and it seems that `new Date()` is evaluated only once in the beginning of the function `setAutoRemoveAsync()` and not after every interval. So the remove query is called with same date argument in every interval.

I have a quite trivial fix for this and could make a pull request, but I don't know what to do with the test set. Can the PR still be accepted if the coverage decreases a fraction of a percent?

**Comment by jdesboeufs** [comment]
Current tests are just 🤮and have to be rewritten.
Feel free to make a PR ;)

**Comment by jdesboeufs** [comment]
Published `3.0.3`

**Comment by jlampise** [comment]
Great! Thank you very much!
