### ISSUE TITLE
Copy session?

### ISSUE THREAD

**Issue by wootwoot1234** [jdesboeufs/connect-mongo#307]
In my project, I want to be able to login to my user's account when handling support tickets.  Is there an easy way to copy a user's session and apply it to my browser so that I can view their account?  

Currently what I do is copy a known hash and salt to their account, then log in to their account, and then put back their original hash and salt but that's time-consuming and I'm sure there is a better way.

**Comment by jas-** [comment]
While I understand your use case, it is dangerous and borderline shady to enable this type of functionality where customers may expect privacy within their account. That being said why not code up the same process you describe as part of your application? It really falls outside the scope of the module imho.

**Comment by wootwoot1234** [comment]
I understand how this feature would be outside the scope of the module and how this could be used used for shady purposes but in my case it's not, I have users that have questions and they appreciate that can see what they see.  I wrote a script that swaps the hash and salt but it would be nice if I didn't even have to go through the login process, it's time-consuming and I do it often when answering support emails.  

I don't mind coding this outside of the module, would you mind explaining to me how you would go about it?

**Comment by jas-** [comment]
Not without a contract to write the code for you.

**Comment by mingchuno** [comment]
I don't think it is a good idea to have session copy functionality in this module too.

**Comment by wootwoot1234** [comment]
@jas- that's not really in the spirit of open source is it.  I'm not asking for any written code, just asking for some advice.

**Comment by jas-** [comment]
Neither is subverting a customers security.

**Comment by farrago** [comment]
I have previously provided this “support can impersonate a user” functionality.  However it was a full feature supported across the application’s authentication, access control, logging and auditing systems. So a support team member can login with their own credentials but with an additional ID of the user being impersonated. In our case we also required a multi-factor confirmation from the impersonated user to allow support to impersonate them. 

From then on the system would work as-if the support person was actually the impersonated user. This access was (a) time limited, (b) logged and audited as “support user foo AS normal user bar” for every action, and (c) blocked from doing certain actions (viewing or changing personal information, changing passwords, etc).

Obviously this is a bigger piece of work than just hacking the session but it is more secure and more auditable. And obviously well outside the scope of this project.
