### ISSUE TITLE
Destroy event

### ISSUE THREAD

**Issue by rfossella** [jdesboeufs/connect-mongo#308]
I do not see any documentation for handling a 'destroy' event.  

Is there something like ```mongoStore.on('destroy', function(session){}) ``` so that I can perform cleanup operations when this occurs?

Thanks!
Rob

**Comment by rfossella** [comment]
Any ideas on this  is this still maintained?  thank you

**Comment by mingchuno** [comment]
Yes, I am the new maintainer but I still need time to pick up.

**Comment by mingchuno** [comment]
@rfossella Do you mean when the session destroy or the mongo connection being destroyed? If it is session destory, we have it on 
https://github.com/jdesboeufs/connect-mongo/blob/3f5cdcc82c933aad83732ab40984e2af595d7b6d/src/index.js#L297

Am I correct?

**Comment by rfossella** [comment]
Thanks for your response.  I'm trying to trap an event when then session is destroyed - i.e. the expiration has timed out.

For example: I have a setting that kills the session after 5 minutes.  I check the mongo collection from a command-line  and it displays the correct expiry.  After 5 minutes I click a link in my site and I'm correctly logged out since session is done.

Coding: I initializing my mongostore and I set up to capture events - e.g.
```
const MongoStore = require('connect-mongo')(session);
const mongoSessionStore = new MongoStore({
		mongooseConnection: db.connection,
		//url: mongoConnStrFull
		ttl: 1 * 60 * 60,		 // = 1 hours
		// autoRemove: 'interval',
		// autoRemoveInterval: 1
		// ttl: 14 * 24 * 60 * 60 // = 14 days. Default
	});
mongoSessionStore
			.on('create', (sessionId) => {  
				console.log({event: 'create', sessionId});
			})
			.on('touch', (sessionId) => {   
				console.log({event: 'touch', sessionId});
			})
			.on('update', (sessionId) => {    
				console.log({event: 'update', sessionId});
			})	
			.on('set', (sessionId) => {   
				console.log({event: 'set', sessionId});
			})
			.on('connect', (sessionId) => {    
				console.log({event: 'connect', sessionId});
			})	
			.on('disconnect', (sessionId) => {   
				console.log({event: 'disconnect', sessionId});
			})
			.on('destroy', (sessionId) => {    
				console.log({event: 'destroy', sessionId});
			})
``` 

The only events that get hit are _create, touch, update and set_.  I was hoping that either 1) the destroy event would get hit when the **session timed out** or 2) based on **ttl** and doc removed.

Again, the session times out correctly; the doc removed based on ttl.  But I never get any type of destroy event.

Hope my explanation is clear.  Thank you!

Rob

**Comment by rfossella** [comment]
Hi.  Any other info needed from me to assist with my question?

**Comment by mingchuno** [comment]
@rfossella So this may be a bug in the code? Do you have any chance to make a simple reproducer repo so that we can try it out to verify the bug?

**Comment by astigmatism** [comment]
I have also discovered this bug.

Looking at the source, it appears the intention is to emit the "destroy" event just after deleting the session from mongo, but just as the original poster noted, it does not occur.

A "reproducer repo" is a barrier for your end-users. The test case is simple: set a low session length and a break point when the "destroy" event is emitted. You'll notice the session document will be destroyed correctly but the event never emits.

**Comment by rfossella** [comment]
astigmatism - thanks for your comment.  Hopefully we can get a push for an update.

**Comment by mingchuno** [comment]
After some study. The `destroy` event only emit when module user call `store.destroy` but not when the session (document) in MongoDB expired. Since we are using the mongodb native mechanism to expire the session (via TTL index) so it is difficult to emit an event when the document got deleted due to TTL index.

**Comment by rfossella** [comment]
So to summarize, this cannot be solved using this module?  This would need to be handled independently by users of this module or will you look further?  Thanks

**Comment by mingchuno** [comment]
Yes, I don't think it is suitable to solve in this module. You can take a look in here to see if any luck...
https://docs.mongodb.com/manual/reference/method/db.collection.watch/
