### ISSUE TITLE
req.logout() isn't logging a user out

### ISSUE THREAD

**Issue by mscraigloewen** [jdesboeufs/connect-mongo#309]
Hello! 
I'm calling the req.logout() function on my logout path, and it isn't logging out my user. I took a look at issue #140 and tried taht implementation to no avail.

I have also tried using req.session.destroy() but after I call that I am then unable to login with any username or password. 

Any ideas on how to fix it?

Thanks!
-Craig

**Comment by jdesboeufs** [comment]
Hello.
Your problem is at a higher level than session persistence. You should have the same behavior with the default MemoryStore.
