### ISSUE TITLE
Mongodb DeprecationWarning

### ISSUE THREAD

**Issue by HelloKevinTian** [jdesboeufs/connect-mongo#330]
- mongodb version：3.2.10

- express-session version：1.16.2

- connect-mongo version：3.0.0

- I found that connect-mongo triggered the warning。

- express server started with warning：

(node:494260) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to MongoClient.connect.

Part of code:
```
        app.use(
            session({
                secret: this.session.secret,
                cookie: {
                    httpOnly: true,
                    maxAge: 1000 * 60 * 60
                },
                resave: true, 
                saveUninitialized: false,
                store: new MongoStore({
                    url: this.session.dbUrl
                })
            })
        );
```

**Comment by mingchuno** [comment]
1. Please edit your title, do not post the whole error message as the title
2. Don't assume everyone knows Chinese here (fortunately I do but not everyone in here). Please try to submit your issue in English

**Comment by HelloKevinTian** [comment]
> 1. Please edit your title, do not post the whole error message as the title
> 2. Don't assume everyone knows Chinese here (fortunately I do but not everyone in here). Please try to submit your issue in English

Thank you with your advise

**Comment by mingchuno** [comment]
After checking out the release note https://github.com/mongodb/node-mongodb-native/releases/tag/v3.2.1

It is a new feature on mongodb drive `v3.2.1` and it said:
`so we strongly encourage our users to try it out as soon as possible.`

I am not sure it is stable enough for downstream (this lib) to use it yet. You can add an extra `mongoOptions` to test it out first and report in here.

```js
new MongoStore({
    url: connectionString,
    mongoOptions: { useUnifiedTopology: true },
})
```

If everything is alright, I can push a commit and add it as a default options

**Comment by bilfr3d** [comment]
any idea when this is going to be pushed to NPM? The NPM package hasn't been updated yet, so users downloading from there still receive the deprecation warning.

**Comment by mingchuno** [comment]
@bilfr3d

**Comment by robertsLando** [comment]
@mingchuno I get this error even when using 

```js
store: new MongoStore({
      mongooseConnection: mongoose.connection,
      mongoOptions: { useUnifiedTopology: true }
    })
```

Mongoose is correctly inited using `useUnifiedTopology: true` I started having this deprectaion warning after updating `connect-mongo` to version `3.0.0`

**Comment by mingchuno** [comment]
```
> npm info connect-mongo

connect-mongo@3.1.0 | MIT | deps: 1 | versions: 45
MongoDB session store for Express and Connect
https://github.com/jdesboeufs/connect-mongo#readme

keywords: connect, mongo, mongodb, session, express

dist
.tarball: https://registry.npmjs.org/connect-mongo/-/connect-mongo-3.1.0.tgz
.shasum: 2a98efa834de7e9e63005e24fec5dcf8d38b3cca
.integrity: sha512-BDn09MMBFse7Y0uVjUW8p7jjDKHWgg0veXFeETqBeJM7Eg+aWN8YBpod5FkSLiD28YknrYjT4dgHg9fq/h62ew==
.unpackedSize: 34.2 kB

dependencies:
mongodb: ^3.1.0

maintainers:
- jdesboeufs <jerome.desboeufs@gmail.com>
- kcbanner <kcbanner@gmail.com>

dist-tags:
beta: 3.0.0-rc.2  latest: 3.1.0

published a minute ago by mingchuno <mingchuno@gmail.com>
```
just published the new version with the `useUnifiedTopology=true` fix

**Comment by mingchuno** [comment]
@rob

> @mingchuno I get this error even when using
> 
> ```js
> store: new MongoStore({
>       mongooseConnection: mongoose.connection,
>       mongoOptions: { useUnifiedTopology: true }
>     })
> ```
> 
> Mongoose is correctly inited using `useUnifiedTopology: true` I started having this deprectaion warning after updating `connect-mongo` to version `3.0.0`

Can you try again with the latest 3.1.0?

> @mingchuno I get this error even when using
> 
> ```js
> store: new MongoStore({
>       mongooseConnection: mongoose.connection,
>       mongoOptions: { useUnifiedTopology: true }
>     })
> ```
> 
> Mongoose is correctly inited using `useUnifiedTopology: true` I started having this deprectaion warning after updating `connect-mongo` to version `3.0.0`

can you try again with the new 3.1.0?

**Comment by robertsLando** [comment]
@mingchuno Still having the same issue

**Comment by robertsLando** [comment]
If I downgrade to version `2.0.3` no deprecation warning shows up

**Comment by bilfr3d** [comment]
I'm still getting the deprecation warning as @robertsLando has mentioned, with version 3.1.0. I have not tried any other version.

`C:\Users\Owner\Documents\content-management-system>node server.js
(node:10192) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future 
version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Listening on: 80
^C
C:\Users\Owner\Documents\content-management-system>npm info connect-mongo

connect-mongo@3.1.0 | MIT | deps: 1 | versions: 45
MongoDB session store for Express and Connect
https://github.com/jdesboeufs/connect-mongo#readme

keywords: connect, mongo, mongodb, session, express

dist
.tarball: https://registry.npmjs.org/connect-mongo/-/connect-mongo-3.1.0.tgz
.shasum: 2a98efa834de7e9e63005e24fec5dcf8d38b3cca
.integrity: sha512-BDn09MMBFse7Y0uVjUW8p7jjDKHWgg0veXFeETqBeJM7Eg+aWN8YBpod5FkSLiD28YknrYjT4dgHg9fq/h62ew==
.unpackedSize: 34.2 kB

dependencies:
mongodb: ^3.1.0 

maintainers:
- jdesboeufs <jerome.desboeufs@gmail.com>
- kcbanner <kcbanner@gmail.com>

dist-tags:
beta: 3.0.0-rc.2  latest: 3.1.0

published 9 hours ago by mingchuno <mingchuno@gmail.com>
`

Here is the code that's initialising the DB:
`[...] client.connect(url, {} [...]`

I'm providing no options, so useUnifiedTopology should default to `true`?

**Comment by robertsLando** [comment]
@mingchuno any news about this?

**Comment by bilfr3d** [comment]
Turns out my error was because I was supplying a separate client - my bad. Letting `connect-mongo` create a client  on its own worked fine. This was the code I ended up using:
```
Store = new (require("connect-mongo")(session))({ url: "mongodb://localhost/mymongo-db" });
```

I'm not using mongoose though, so perhaps the settings are being changed when `connect-mongo` is being supplied with an existing mongoose connection, instead of creating its own connection.

**Comment by bilfr3d** [comment]
@robertsLando I just tried using the exact code you have there, both with and without the `await` - the code works fine for me. Are you sure connect-mongo had updated to `3.1.0`? Perhaps try updating it again, or using a new package directory.

**Comment by robertsLando** [comment]
Yes I’m sure, the strange thing is that with or without the changes made in version 3.1.0 my code should work as the changes simply set the flag (useUnified...) has been set by default to true when providing an url in options. In my case connect-mongo should just take my connection as it is and use it. It is really strange that throws that error I have tried to debug it without success

Daniel

**Comment by robertsLando** [comment]
@mingchuno My fault, there was a packet using a different version of MongoCLient that was throwing the error. Now it works and this can be closed
