### ISSUE TITLE
Error:Connection strategy not found!

### ISSUE THREAD

**Issue by rawatnaresh** [jdesboeufs/connect-mongo#332]
I was trying to use MongoStore with native mongodb driver. This is how my configuration looks liks
```
//  imports
const express = require('express');
const session = require('express-session');
const mongoClient = require('mongodb').MongoClient;
const MongoStore = require('connect-mongo')(session);

//  express app
const app = express();

//  connecting to mongodb

mongoClient.connect('url', options, (err, client) => {
 if (err) {
    console.log('MongoDB connection error.');
    return;
  }
//  connection successful

  console.log(client.isConnected(), 'isConnected'); //getting 'true'

//   setup express session once connected to db

  app.use(session({
    name: 'mysession',
    store: new MongoStore({ client }),
    secret: 'SESSION_SECRET',
    touchAfter: 24 * 3600,
    resave: false,
    saveUninitialized: false,
    cookie: { maxAge: 1000 * 60 * 15 },
  }));

// finally listening to port 8080

 app.listen(8080,console.log('listening'));
  });
```

I'm connected to the database successfully but when I pass the instance of MongoClient to the MongoStore I'm getting an error saying _Connection strategy not found_ .

I also looked into the source code to see the options MongoStore is accepting and it has these two checks `options.client` && `options.client.isConnected()` before handling the core-mongo connection which are true in this case.

I'm not sure what I'm doing wrong here. It's working fine with the mongoose though.

**Comment by dman777** [comment]
I am hitting this also. I am trying use a existing  mongo db pool:

```javascript
const initMongoStore = (mongoPool) => {
  const uuid = require('node-uuid');

  app.use(session({
    secret: 'foobar',
    keys: ['isAuth', 'userID', 'echoEnabled'],
    store: new MongoStore({ client: mongoPool }),
    saveUninitialized: false,
    resave: false,
    cookie: {
      secure: false,
      httpOnly: false,
      genid: uuid.v1(),
      maxAge: 86400 * 1000 * 30 * 12,
    }
  }));
};
```

**Comment by dman777** [comment]
Using `db` instead of `client` worked for me.

 However, I don't know if I am working off of side effect or I am correctly using this with `db`. @jdesboeufs , could you  please confirm since documentation states differently?  

```javascript
const initMongoStore = (mongoPool) => {
  const uuid = require('node-uuid');

  app.use(session({
    secret: 'bob',
    keys: ['isAuth', 'userID', 'echoEnabled'],
    store: new MongoStore({ db: mongoPool }),
    saveUninitialized: false,
    resave: false,
    cookie: {
      secure: false,
      httpOnly: false,
      genid: uuid.v1(),
      maxAge: 86400 * 1000 * 30 * 12,
    }
  }));
};
```

**Comment by NuclearPumpkin** [comment]
@dman777 are you sure your sessions are being stored? I looked into the code and `MongoStore` doesn't accept db as options.

**Comment by guyellis** [comment]
@NuclearPumpkin is right that in the target code `db` is not an option.

@dman777 - any chance you were looking at the TypeScript types? They seem to be wrong. There's an interface `NativeMongoOptions` which has `db` as an option but it doesn't match the actual code.

**Comment by mingchuno** [comment]
Yes. Do not look at the ts type. Can you guys provide the version you are using on the following?

- mongodb version
- mongodb native js driver version
- express-session version
- connect-mongo version

**Comment by popod** [comment]
HI, same error for me after updating to latest `connect-mongo` version (I use latest `mongoose` version).

Change property `db` by `client` then throw this error:

```
TypeError: mongoose.connection.isConnected is not a function
```

Any idea to resolve this ? thanks

**Comment by NuclearPumpkin** [comment]
It doesn't work with an existing connection. So instead of using an existing connection you can pass the connection url to the mongoStore and it'll just work fine.
```
const MONGO_URI = 'mongodb_url'
const store = new MongoStore({
  url: MONGO_URI,
});
app.use(session({
  name: 'mysession',
  store: new MongoStore({ client }),
  secret: 'SESSION_SECRET',
  touchAfter: 24 * 3600,
  resave: false,
  saveUninitialized: false,
  cookie: { maxAge: 1000 * 60 * 15 },
}));
```

**Comment by MikeRossXYZ** [comment]
The problem I believe is that the documentation makes it seem like the `client` option was a straight-up replacement for the `db` option, which it is not. I was getting the same `isConnected is not a function` error as you.

In version 3.x.x of this library, you should use a `MongoClient` object (https://mongodb.github.io/node-mongodb-native/3.5/api/MongoClient.html) as the `client` option, not a `Db` object (https://mongodb.github.io/node-mongodb-native/3.5/api/Db.html) that was used in version 2.x.x.

**Comment by som-cs** [comment]
was anyoone able to solve this?

**Comment by naveenkash** [comment]
`
const session = require("express-session");
const MongoStore = require("connect-mongo")(session);

const store = new MongoStore({
  url: process.env.MONGO_URI,
});
const cookie_max_age = 1000 * 60 * 60 * 168; // one week
app.use(
  session({
    name: "sid",
    secret: process.env.SECRET_TOKEN || "secret",
    resave: false,
    saveUninitialized: false,
    cookie: {
      secure: false,
      maxAge: cookie_max_age,
      sameSite: true,
    },
    store:store,
  })
);`

this worked for me
