### ISSUE TITLE
Throwing an error on startup: TypeError: Cannot read property 'MemoryStore' of undefined

### ISSUE THREAD

**Issue by omaxanderson** [jdesboeufs/connect-mongo#333]
I'm using connect-mongo with fastify and fastify-session, which allows for express-session compatible stores. On startup, connect-mongo is throwing an error: 'TypeError: Cannot read property 'MemoryStore' of undefined'.

I know this is specifically an Express plugin, but I'm wondering if it would be possible to add some handling to make it slightly more compatible with non-Express session plugins. 

In src/index.js if I change `const MemoryStore = connect.MemoryStore || connect.session.MemoryStore` to `const MemoryStore = connect.MemoryStore || (connect.session && connect.session.MemoryStore)`, everything works great. 

Let me know what you think. Thanks!

**Comment by aroojahmad** [comment]
Similar problem:

Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
 /app/node_modules/connect-mongo/src/index.js:56
const Store = connect.Store || connect.session.Store

TypeError: Cannot read property 'Store' of undefined

**Comment by aroojahmad** [comment]
const sessionStore = new MongoStore({ mongooseConnection: mongoose.connection });

Using sessionStore in all necessary app.use instances. What's the problem?

**Comment by aroojahmad** [comment]
Got it working finally, here is the code I used to get everything working:

const session = require('express-session');
const MongoStore = require('connect-mongo')(session);

.
.
.

const sessionStore = new MongoStore({ mongooseConnection: mongoose.connection });

.
.
.
app.use(session({
  secret: `${process.env.SECRET}`,
  resave: false,
  store: sessionStore,
  saveUninitialized: true
}));

**Comment by mingchuno** [comment]
Yes. You should supply the mongo/mongoose client to the MongoStore so that it won't use the default `MemoryStore`.
