### ISSUE TITLE
chore: always use yarn

### ISSUE THREAD

**Issue by DanielRuf** [jdesboeufs/connect-mongo#337]

**Comment by mingchuno** [comment]
@DanielRuf I don't get it here. We are using `yarn` already.

**Comment by DanielRuf** [comment]
Not here and probably a few other places too ;-)

**Comment by DanielRuf** [comment]
Not here and probably a few other places too ;-)

https://github.com/jdesboeufs/connect-mongo/blob/master/.travis.yml#L29

**Comment by mingchuno** [comment]
I think it doesn't matter using npm in that line for that case?

**Comment by DanielRuf** [comment]
Sorry, I had not much time to answer.

It makes a difference due to the lockfile.

**Comment by mingchuno** [comment]
I don't quite get it..? the npm install is to global

**Comment by DanielRuf** [comment]
Right. But consistent results and using the same makes more sense.

Not sure why you want to mix npm and yarn in CI.

Anyway, thanks for taking the time for your feedback.
