### ISSUE TITLE
TypeScript Definition

### ISSUE THREAD

**Issue by guyellis** [jdesboeufs/connect-mongo#338]
How do you feel about moving the Definitely Typed TypeScript definition file into this repo to better keep the source insync with the TypeScript definitions?

**Comment by mingchuno** [comment]
@guyellis would you mind provide me some link or doc to kick start? PR directly is welcome too.

**Comment by guyellis** [comment]
Problem: Nobody is maintaining the TypeScript definition for connect-mongo so the types from previous versions are the latest. I've submitted a pull request here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39278

Further problem: Issues might be created in this issue tracker because of confusion about the API of connect-mongo because of the mismatched types. For example, is @dman777 using an old type in this comment https://github.com/jdesboeufs/connect-mongo/issues/332#issuecomment-526713782 which is the problem as I mentioned a couple of comments later.

By copying that type file from DefinitelyTyped into this repo as a first step it will provide a single place to update the API and the type definitions. If connect-mongo is bumped to another major then somebody will have to remember (catch) to update the types.

If we wanted to take it one step further we could change the tests in this repo to TypeScript. This would allow them to use the declared types and if the target code were to change the type changes would be forced and thereby keeping them in sync. However, I'm not suggesting this right now. This is just an idea to keep the types in-sync. This issue and question is just to pull the type definitions into this repo.

The changes would be:

- Copy my PR'd version of the DefinitelyTyped file into this repo.
- Add a `"types": "./lib/types.d.ts"` to the package.json file.

I can PR this if you think this acceptable?

**Comment by mingchuno** [comment]
@guyellis Yes, sure! Thank you for your details explanation.

**Comment by guyellis** [comment]
@mingchuno - can you bump the version with a Minor and publish so these definitions are available? Thanks.

**Comment by mingchuno** [comment]
okay, will do it tonight
