### ISSUE TITLE
Why should I use it over JWT?

### ISSUE THREAD

**Issue by natvaldev** [jdesboeufs/connect-mongo#345]
I'm just wondering about the essence of this library.
Is it for storing auth data?

If so, what are the pros over a `jwt`?

**Comment by mingchuno** [comment]
@natvaldev looking for something like this?
https://stackoverflow.com/questions/37582444/jwt-vs-cookies-for-token-based-authentication

**Comment by natvaldev** [comment]
No exactly, I don't ask about storing the token or key in this case,
but why shouldn't I store the `jwt` and verify it for every request?
Instead of storing some generated id and query the `db` for every request?

**Comment by jdesboeufs** [comment]
`jwt` is handful.
A regular session is more secure and often lightweight (in bytes).

Depending on what you have to put in your `jwt`, you decide ;)
