### ISSUE TITLE
Weird behavior.

### ISSUE THREAD

**Issue by oOBlinkOo** [jdesboeufs/connect-mongo#347]
Hello, i have a issue im not sure if this is a valid behavior or not but i already have my conf like this:
```
app.use(session({
  store: new MongoStore({ 
    url:  mongoConnectionString,
    dbName:mongoDatabaseString,
    collection:'mySessions',
  }),
  cookie: { 
    maxAge: null,
  }, // 1 week
  saveUninitialized:true,
  resave:true,
  secret: 'test'
}));
  app.use(logger);
```
sometimes when i receive the connect.sid from browser it is creating a new one
<img width="1280" alt="Screen Shot 2019-12-26 at 4 43 13 PM" src="https://user-images.githubusercontent.com/5222538/71492669-bcbe8380-27fe-11ea-9e70-fe9329be9229.png">
![Screen Shot 2019-12-26 at 4 45 19 PM](https://user-images.githubusercontent.com/5222538/71492707-fe4f2e80-27fe-11ea-83f0-8fa62f5a1264.png)
in this example it is creating zumSKtkRC4086x9XZ6q9zVyeZIZMemxD when JSVnP4q6WiII2ebE61fIgaZH0Rwg9H1X it is already  created. This happen sometimes.

The normal behaviour once that is the sid is already created all the next request get the same sid.

<img width="1287" alt="Screen Shot 2019-12-26 at 4 51 02 PM" src="https://user-images.githubusercontent.com/5222538/71492825-da401d00-27ff-11ea-8106-615973acd5cc.png">

Any help it will be appreciated

**Comment by jas-** [comment]
When this occurs are you using any type of CSRF token, or perhaps sending the wrong cookie?

A complete transaction log and application configuration would help.

**Comment by oOBlinkOo** [comment]
if you see the img sessionID is the value from the cookie in my web browser, but sometimes it generate a new one. Im not creating any CSRF token just the token that the library create for my sessionID and this is passed to my front end then in the next call to the backend the value is sent with the last value. that is the moment when it could be generate a new one or work with the current.

**Comment by jas-** [comment]
Does this happen without the transparent encryption?
