### ISSUE TITLE
Bug - property dbName does not exist

### ISSUE THREAD

**Issue by Ekman** [jdesboeufs/connect-mongo#352]
I see that #349 was merged that should've fixed this, but it still doesn't work.

If you go to the package in [npmjs.org](https://www.npmjs.org), [click on "Explore"](https://www.npmjs.com/package/connect-mongo?activeTab=explore) and go to `src/types.d.ts` then the type definition still does not include `dbName`. The first line of `types.d.ts` reads `// Type definitions for connect-mongo 3.1`, even though it is 3.2 that is the latest.

**Comment by Ekman** [comment]
Quick fix is to add `// @ts-ignore` above the `dbName` line.

**Comment by Ekman** [comment]
This is still an issue

**Comment by mingchuno** [comment]
I haven't bumped a new version and release yet ... I will bump the version after I clean up all the issues and PRs. I may also publish a beta version first. Will update you when it is done.

**Comment by ihgrant** [comment]
Any progress on this? Is there anything I can help with?

**Comment by ihgrant** [comment]
This is still an issue... @mingchuno is there a holdup that I can help with?

**Comment by ihgrant** [comment]
This is still an issue.

**Comment by mingchuno** [comment]
@Ekman @ihgrant I have just rewrite the code using TS and published a new version! Can you please help me try it out to see of it fix your issue? https://www.npmjs.com/package/connect-mongo
