### ISSUE TITLE
req.session.destroy() does not clear cookie on client

### ISSUE THREAD

**Issue by vibonacci** [jdesboeufs/connect-mongo#354]
After using req.session.destroy(err) callback, the req.session is properly set to null and the session is removed from the sessions Mongo Collection. However, cookie remains present in clients browser. While the .sid on the browser is now invalid, it should be completely removed from clients browser.

I looked through all settings. Anything setting I am missing? Or is this recommended behavior?

**Comment by vibonacci** [comment]
Manually clearing cookie using Express' res.clearCookie works, however, I am still wondering whether the session store implementation is not responsible for this?

`/** Logout */
router.post('/logout', (req, res) => {
  if (req.session && req.session.user) {
    req.session.destroy((err) => {
      if (err) {
        console.error('error destroying existing session: ' + err)
      }
      else {
        res.clearCookie(process.env.APP_NAME + '.sid').status(200).send('Successful logout and manual clear cookie!')
      }
    })
  } else {
    res.status(200).send('No valid session present!')
  }
})`

**Comment by jas-** [comment]
@vibonacci Server side sessions don't unset client side cookies.

Please review the documentation for the requisite [session]() middleware paying attention to the `Session.destroy(callback)` & `store.destroy(sid, callback)`  functions. Both of which exclusively handle server side session data.

The [express](https://expressjs.com/en/api.html) function [.clearCookie()](https://expressjs.com/en/api.html#res.clearCookie) is the correct function to use if you wish to unset expired or invalidated session data and its referenced cookie.

**Comment by sayhicoelho** [comment]
For anyone experiencing this issue, here is a code snippet to logout a user:

```js
exports.logout = (req, res, next) => {
  req.session.destroy(err => {
    if (err) {
      next(err)
    } else {
      res.clearCookie('connect.sid')
      res.redirect('/')
    }
  })
}
```

**Comment by guvenfazli** [comment]
> For anyone experiencing this issue, here is a code snippet to logout a user:
> 
> ```js
> exports.logout = (req, res, next) => {
>   req.session.destroy(err => {
>     if (err) {
>       next(err)
>     } else {
>       res.clearCookie('connect.sid')
>       res.redirect('/')
>     }
>   })
> }
> ```
> 
> This will remove the user's session from the database and will remove the cookie on the client side.

Thank you.
