### ISSUE TITLE
types.d.ts has a hard dependency on mongoose, which is optional.

### ISSUE THREAD

**Issue by Radio** [jdesboeufs/connect-mongo#355]
Mongoose is used in types definitions, but the mongoose library itself is not required by the package.

**Comment by Radio** [comment]
Quick fix for projects that use connect-mongo without mongoose: add mongoose types as dependency: `npm install @types/mongoose`

**Comment by vansergen** [comment]
The following code 
```ts
import * as session from "connect-mongo";
console.log(session);
```
cannot be compiled (assuming the only installed packaged is `connect-mongo`) with the following errors:

```
node_modules/connect-mongo/src/types.d.ts:10:26 - error TS2307: Cannot find module 'express'.
node_modules/connect-mongo/src/types.d.ts:11:27 - error TS2307: Cannot find module 'mongoose'.
node_modules/connect-mongo/src/types.d.ts:12:26 - error TS7016: Could not find a declaration file for module 'mongodb'.
node_modules/connect-mongo/src/types.d.ts:13:26 - error TS2307: Cannot find module 'express-session'.
node_modules/connect-mongo/src/types.d.ts:113:58 - error TS2503: Cannot find namespace 'Express'.
node_modules/connect-mongo/src/types.d.ts:114:37 - error TS2503: Cannot find namespace 'Express'.
node_modules/connect-mongo/src/types.d.ts:118:39 - error TS2503: Cannot find namespace 'Express'.
```
@jdesboeufs How do you feel about moving devDependencies `@types/express-session` and `@types/mongoose` to the list of dependencies? If you are ok with this change, I will open a new PR.

**Comment by rfox12** [comment]
+1 for this issue.  Please don't require mongoose.

**Comment by vansergen** [comment]
Ping

**Comment by mingchuno** [comment]
@vansergen @Radio How about adding `npm install --save-dev @types/express-session @types/mongoose` into the README for those who are using TS. Does that solve the issue?

**Comment by Radio** [comment]
@mingchuno I‘d say this is a workaround, not a solution. I actually proposed this as a workaround in my second comment :)

**Comment by mingchuno** [comment]
Or better, we should add `@types/connect-mongo` and put all the typedef and depends there

**Comment by vansergen** [comment]
> Or better, we should add `@types/connect-mongo` and put all the typedef and depends there

I think the idea of #339 was to keep the types in this repo. We should add `@types/express-session` and `@types/mongoose` either to `dependencies` or to `peerDependencies`
