### ISSUE TITLE
Session not persistent after app restart

### ISSUE THREAD

**Issue by BetaHuhn** [jdesboeufs/connect-mongo#358]
I am using connect-mongo with mongoose. When I login a session is created and stored in the DB. When I close the browser and reopen the website the cookie is sent and I am still logged in. Everything working as it should. 

But if I restart my Node.js App and reload the website I have to login again. I checked the headers which where send and the cookie was still in there. Also the session was still in the DB. It seems as if connect-mongo or express-session doesn't recognize the session id after a restart. I thought that was the point of a DB as a session store instead of a memory store.

Here is my main code:
```
mongoose.connect(url, options, )
        .then(() => {
            console.log('Database connection successfull: ' + database)
            return mongoose
        })
        .catch(err => {
            console.error('Fucked up while connecting to the database: ' + err)
            process.exit();
        })

var mongoStore = new MongoStore({
    mongooseConnection: mongoose.connection,
    collection: 'sessions'
});

app.use(session({
    secret: crypto.randomBytes(64).toString("base64"),
    resave: true,
    saveUninitialized: false,
    cookie: {
        secure: false,
        maxAge: 15 * 60 * 60 * 1000,
        sameSite: "lax"
    },
    store: mongoStore
}));
```

**Comment by jas-** [comment]
@BetaHuhn you have generated a new session secret once the application is restarted thereby invalidating your old sessions and the cookies sent from the client

**Comment by BetaHuhn** [comment]
Of course, how did I miss that?! Tried everything, but didn't notice that. Some tutorial i followed used that function and I just copied that when setting everything up. Thanks!
