### ISSUE TITLE
impact by proposed changes to express-session

### ISSUE THREAD

**Issue by ghinks** [jdesboeufs/connect-mongo#361]
An [issue was raised](https://github.com/expressjs/session/issues/711) against express-session and an [accompanying PR has been raised](https://github.com/expressjs/session/pull/712). 

The proposal would be to conditionally pass extra parameters to express-session stores such as connect-mongo. This proposal has been raised by @boenrobot. It would allow the store to distribute storage on a per host request basis. With different DBs being used for requests with a different host.

I would value any time you give offering your opinion on the value of such a proposal.

**Comment by mingchuno** [comment]
@ghinks I have read that PR and will close this issue first. Please raise PR or re-open this if you guys feel the need to. Also feel free to loop me in for further discussion.
