### ISSUE TITLE
TimeoutOverflowWarning if autoRemoveInterval is greater than 2592000000 

### ISSUE THREAD

**Issue by tsmgeek** [jdesboeufs/connect-mongo#362]
Implement check if user sets timeout greater than 32-bit signed integer as otherwise it defaults to 1ms for `autoRemoveInterval`.
This can happen by mistake if user forgets that interval is in mins not seconds.

```
(node:1) TimeoutOverflowWarning: 2592000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

**Comment by mingchuno** [comment]
@tsmgeek fixed in https://github.com/jdesboeufs/connect-mongo/commit/75babe48d62a5183fbc094cac4e109644265c1d2
