### ISSUE TITLE
Security - vulnerabilities found 16 Moderate | 10 High | 3 Critical 

### ISSUE THREAD

**Issue by abhidilliwal** [jdesboeufs/connect-mongo#367]
There are **3** critical and **10** high vulnerabilities according to `yarn audit`

```
Severity: 40866 Low | 16 Moderate | 10 High | 3 Critical
```

**Comment by YasharF** [comment]
I am using npm instead of yard and got the warning to go away by either running `npm update bl --depth 3`, or deleting package-lock.json and regenerating it.

**Comment by taylortom** [comment]
Looks like this was only just fixed in mongodb@3.6.2 (11 days ago)

**Commit**: https://github.com/mongodb/node-mongodb-native/commit/c16ec43a3cd9a751c11b10b1b6b2bc3cc4d933c4
**Release**: https://github.com/mongodb/node-mongodb-native/releases
