### ISSUE TITLE
secret key does not work

### ISSUE THREAD

**Issue by sam13591980** [jdesboeufs/connect-mongo#370]
As I understood the secret key option in connect-mongo, causes that the _id of the session inside the session store in db encrypted by the secret key and send it to client as cookie. But actually I could see the same id in the db inside the cookie (No matter what I choose as secret key). This is happens even if I make secure:true and httpOnly:false.
Is this a bug or maybe I understood wrongly the usage of secret key?

Thanks

**Comment by jas-** [comment]
The `_id`? No, the ID is how the session store retrieves the session data which is referenced by the cookie provided by the client.

**Comment by sam13591980** [comment]
> The `_id`? No, the ID is how the session store retrieves the session data which is referenced by the cookie provided by the client.

So what is the point of secret key? what it does? if I suppose to send exactly store the same data that I am sending to the client? do you mean it encrypt those data in db instead via secret key?

**Comment by jas-** [comment]
In accordance with [OWASP Session management](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html), enabling transparent encryption of session data; that is session information residing on the server which correlates to the client cookie, can be optionally encrypted if said data is sensitive in nature.

Referenced information
`If the session objects and properties contain sensitive information, such as credit card numbers, it is required to duly encrypt and protect the session management repository.`

The session information is stored in the mongo database, and if a secret is provided that information is encrypted with the derived key obtained from the original secret provided.

I hope that clears up the confusion, perhaps the documentation is not adequate?
