### ISSUE TITLE
Crypto issues

### ISSUE THREAD

**Issue by jas-** [jdesboeufs/connect-mongo#372]
The following issues are present in the current crypto implementation.

Issues with error handling:
- Fails to handle exceptions for key derivation, encrypt & decrypt functions.

- [Incorrect size & non-unique value](https://github.com/jdesboeufs/connect-mongo/blob/master/src/crypto.js#L18) for additional authentication data (AAD) when using AEAD mode of cipher(s). The current implementation combines two non-unique values which may not meet the complexity or length requirements; References: [NIST SP 800-38D](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf)

Encoding failures:
- When character sets for Unicode are used failures to decrypt occur.

To resolve PR #348 moves away from the current crypto class to the [kruptein](https://www.npmjs.com/package/kruptein) module which conforms to the [industry standards](https://www.npmjs.com/package/kruptein#cryptography-references) for symmetric encryption and key management.

**Comment by jas-** [comment]
Please fix

**Comment by mingchuno** [comment]
@jas- I have just rewrite the code using TS and published a new version! Can you please help me try it out to see of it fix your issue? https://www.npmjs.com/package/connect-mongo

**Comment by jas-** [comment]
Thanks, I was reading through [https://github.com/jdesboeufs/connect-mongo/blob/master/src/lib/MongoStore.spec.ts#L253](the comments) and it says 'buggy'? I am firing up a test project to work with the new release and thought you might be able to elaborate?

**Comment by mingchuno** [comment]
I have tried to re-implement the crypto login referencing your PR. But  I found that somehow the result from `store.get` becomes stringified version of the underlying session instead of POJO. I must have some error in my code but I didn't have enough time to invistage. Therefore I mark is as "buggy" and would like to come back on this issue later. It would be great if you can help test and debug the crypto part 🙏🏻

**Comment by jas-** [comment]
Issue tracking in #393.
