### ISSUE TITLE
TypeScript | Namespace 'global.Express' has no exported member 'SessionData'

### ISSUE THREAD

**Issue by DmytroMysak** [jdesboeufs/connect-mongo#373]
Recently I updated my nestjs app to version 7 as result I got 3 errors:
![image](https://user-images.githubusercontent.com/22196591/99956465-bcbc6000-2d8e-11eb-8260-0dbfb1d97bc1.png)

Please, update types to prevent this errors.
It appears the SessionData interface was removed from the global Express namespace, at the former line 24 on October 13, and recently published in the corresponding DefinitelyTyped modules:
https://github.com/HoldYourWaffle/DefinitelyTyped/commit/0cec4865fe7fd873952fc6901553a96648a7c889#diff-c38f30a0fdd238f104a7392ff3881fa97d8b4497d75e9617163ac1b5fceb75bf

**Comment by gritschf** [comment]
maybe it's enough to change the import to `import { Store, SessionData, SessionOptions } from 'express-session';` ?

**Comment by DmytroMysak** [comment]
> maybe it's enough to change the import to `import { Store, SessionData, SessionOptions } from 'express-session';` ?

Yes, but we need to do it inside connect-mongo package

**Comment by paulkre** [comment]
Is there a workaround for this?

**Comment by YC** [comment]
> Is there a workaround for this?

```
"connect-mongo": "^3.2.0",
"@types/express": "^4.17.9",
"@types/express-session": "1.17.0",
```
seems to work for me.

**Comment by cajoy** [comment]
Any ETA?

**Comment by samal-rasmussen** [comment]
You can reference a github commit directly in your package.json and make use of the fix from @mingchuno like this:
```"connect-mongo": "jdesboeufs/connect-mongo#527f9b6cd3d95d9bcd765c9ef9f2b5705611f9f5",```

That is a workaround until there is a new official npm package release.

**Comment by mingchuno** [comment]
Hi folks, I am currently rewriting the whole package using Typescript and hope to resolve those typing issue and other issue once and for all. Stay tuned
