### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by Dunky13** [jdesboeufs/connect-mongo#375]
We are looking for a Mongoose session store and this library came up. But due to the nature of our project we need active libraries, and this library hasn't had a release for > 1 year. I understand that COVID could have impacted the development of this repository, so that's why I am posing this question.

**Comment by mingchuno** [comment]
Yes! @Dunky13 I have just rewrite the code using TS and published a new version! Can you please help me try it out to see of it fix your issue? https://www.npmjs.com/package/connect-mongo

**Comment by Dunky13** [comment]
I will check it out and let you know, thanks!
