### ISSUE TITLE
UnhandledPromiseRejectionWarning: MongoError: (Unauthorized) not authorized on admin to execute command { insert: "system.indexes", documents: [[{ns admin.sessions} {key [{expires 1}]} {name expires_1} {expireAfterSeconds 0} {unique false}]], ordered: true }

### ISSUE THREAD

**Issue by IzaGz** [jdesboeufs/connect-mongo#379]
Please fix this, i have tried to provide url without srv
but getting
`err = new MongoError(options);
          ^
MongoError: connection 0 to  THE MONGO URL ` closed

Any help? Any alternatives?

**Comment by mingchuno** [comment]
Close due to duplicated with #380
