### ISSUE TITLE
(node:20256) UnhandledPromiseRejectionWarning: MongoError: (Unauthorized) not authorized on admin to execute command { insert: "system.indexes", documents: [[{ns admin.sessions} {key [{expires 1}]} {name expires_1} {expireAfterSeconds 0} {unique false}]], ordered: true }

### ISSUE THREAD

**Issue by IzaGz** [jdesboeufs/connect-mongo#380]
Please fix this,

> (node:20256) UnhandledPromiseRejectionWarning: MongoError: (Unauthorized) not authorized on admin to execute command { insert: "system.indexes", documents: [[{ns admin.sessions} {key [{expires 1}]} {name expires_1} {expireAfterSeconds 0} {unique false}]], ordered: true }

 i have tried to provide url without srv
but getting
`err = new MongoError(options);
          ^
MongoError: connection 0 to  THE MONGO URL ` closed

Any help? Any alternatives?

**Comment by mingchuno** [comment]
@IzaGz I have just rewrite the code using TS and published a new version! Can you please help me try it out to see of it fix your issue? https://www.npmjs.com/package/connect-mongo
