### ISSUE TITLE
Update mongodb dependency

### ISSUE THREAD

**Issue by karstens** [jdesboeufs/connect-mongo#384]
Hi,

first I like to say: great package. 

I wonder, if it is possible to release this package with a newer version of mongodb?

The current used version of connect-mong@3.2.0 uses mongodb@3.3.5 which uses bson@1.1.3, which has a security vulnerabilities, see [bson@1.14 release notes](https://github.com/mongodb/js-bson/releases/tag/v1.1.4)

MongoDB was updated [here](https://github.com/mongodb/node-mongodb-native/commit/e43d39a40ea38198ef35882bf760ec08ddb429b0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) to use bson@1.1.4.

Is it possible to use a newer mongodb release?

Thanks,
Frank

**Comment by mingchuno** [comment]
@karstens I am currently rewriting the package with typescript and will update the mongodb depns at the same time. Stay tuned!

**Comment by mingchuno** [comment]
@karstens I have just rewrite the code using TS and published a new version! Can you please help me try it out to see of it fix your issue? https://www.npmjs.com/package/connect-mongo

**Comment by karstens** [comment]
@mingchuno That is great news, i will do it today! Thank you!

**Comment by mingchuno** [comment]
@karstens After released V4. There are still some bug fix on going. You may need to check out `npm install connect-mongo@next` too. Will try to fix those bugs and relasae 4.2 soon

**Comment by karstens** [comment]
@mingchuno Issue is fixed! Thank you.
