### ISSUE TITLE
Removing expired sessions after migrating to V4.

### ISSUE THREAD

**Issue by goto1** [jdesboeufs/connect-mongo#388]
- **I'm submitting a ...**
  [x] question about how to use this project

- **Summary**

Hello, thank you for this great package.

I have a question related to changes in `V4` for the `autoRemove` and `autoRemoveInterval` feature. 

In `V3` I was able to use `autoRemove: interval` & `autoRemoveInterval: 20`, which sounds like a different behavior than what I would get with `autoRemove: native` that creates a `TTL` index at startup using `MongoDB's` TTL collection feature.

In `V4`, it looks like I can disable the `MongoDB's` TTL collection feature by setting `createAutoRemoveIdx: false`, but it doesn't look like it's going to remove expired sessions similarly to what was available in `V3` - does this mean that expired sessions will have to be removed manually now?

The issue I am running into is that I am using `Azure Cosmos DB`, which works a little differently than a "native" `MongoDB` instance so I am unable to use the `TTL` collection feature.

Any tips or clarifications would be greatly appreciated.

Thanks!

**Comment by mingchuno** [comment]
You are correct. I have removed the `autoRemove` & `autoRemoveInterval` and rely only on TTL collection feature. If you have a legit use case. I think I can add back the options

**Comment by goto1** [comment]
@mingchuno thank you for your response.

I wanted to confirm that's still the case, and it appears to be, but the problem I am running into is because I am using `MongoDB` with `Azure Cosmos DB` and according to the [docs](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-time-to-live#ttl-indexes),

> _ts is a Cosmos DB-specific field and is not accessible from MongoDB clients. It is a reserved (system) property that contains the timestamp of the document's last modification.

I used `autoRemove: "interval"` and `autoRemoveInterval: 10` in `V3` based on the suggestion I found on [StackOverflow](https://stackoverflow.com/a/59639124/5862900) as a workaround.

In case if needed, following migration steps for `V4`, when I remove `autoRemove` & `autoRemoveInterval` and rely on the `createAutoRemoveIdx` option, I get an error message related to the issue described above:

```
(node:7826) UnhandledPromiseRejectionWarning: MongoError: The 'expireAfterSeconds' option is supported on '_ts' field only.
    at MessageStream.messageHandler (/home/xx1234/Development/my-project/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/home/xx1234/Development/my-project/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/xx1234/Development/my-project/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.ondata (internal/streams/readable.js:719:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:131:14)
```

Thanks for all the help so far!

**Comment by mingchuno** [comment]
@goto1 released in 4.2.0. Please check
https://github.com/jdesboeufs/connect-mongo/commit/8c1d180d43c9bc8816808410b0aaa38dfdfcbcd3

**Comment by goto1** [comment]
@mingchuno works beautifully, thank you!

Would you take a PR that updates the [more options](https://github.com/jdesboeufs/connect-mongo#more-options) section and puts back the `autoRemove` & `autoRemoveInterval` options?

Thanks again!

**Comment by mingchuno** [comment]
@goto1 Ya I missed that. Let me add it back

**Comment by goto1** [comment]
@mingchuno thank you for your prompt responses, much appreciated!

Have a good rest of the week.
