### ISSUE TITLE
Question: Dropped support for Mongoose?

### ISSUE THREAD

**Issue by Abourass** [jdesboeufs/connect-mongo#389]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
 I noticed that mongoose is now only supported in version 3. Are you eventually going to add mongoose support back in, or plan to exclude it going forward? Thank you!

**Comment by mingchuno** [comment]
For the simplicity of the library. I drop the ability to use mongoose instance directly when constructing `MongoStore`. I expect one can create a native client first and then supply it to both `mongoose` and `connect-mongo`. Can we?

**Comment by cybay** [comment]
Why do not stand this clearly - there is not any more such abilities that you used to.  And an ability to utilize existing mongoose connection as one of them. 
It could be at least respectful to your users.

As for me - I waste several hours to find the way how to adopt my web-app after updating to 4.1.
 And now I see that it's simply impossible (((

Do you think that it's so obvious or funny enough???

**Comment by mingchuno** [comment]
@cybay @Abourass Please checkout my example in `develop` branch
https://github.com/jdesboeufs/connect-mongo/blob/develop/example/mongoose.js

**Comment by cybay** [comment]
A lot of thanks for reply and help!
It does work, the problem solved.

But any way - let your users/clients save their Time.
It's worth it!

**Comment by Enado95** [comment]
> @cybay @Abourass Please checkout my example in `develop` branch
> https://github.com/jdesboeufs/connect-mongo/blob/develop/example/mongoose.js

This page is no longer available. Can you share how this was resolved?

**Comment by cybay** [comment]
https://github.com/jdesboeufs/connect-mongo/blob/master/example/mongoose.js

In here you can see actually the same.

**Comment by Enado95** [comment]
> https://github.com/jdesboeufs/connect-mongo/blob/master/example/mongoose.js
> 
> In here you can see actually the same.

Thanks!

**Comment by Enado95** [comment]
Get the following error: 

```
(node:1) UnhandledPromiseRejectionWarning: MongoServerSelectionError: connection timed out
    at Timeout._onTimeout (/app/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```
