### ISSUE TITLE
Mongoose connection

### ISSUE THREAD

**Issue by adamhavel** [jdesboeufs/connect-mongo#397]
I have an issue using Mongoose connection as shown in the provided example. I connect to MongoDB this way:

```
const { connection } = await mongoose.connect(`mongodb://mongo:${dbPort}/${dbName}`, {
     useUnifiedTopology: true,
     useNewUrlParser: true,
     useCreateIndex: true
});
```

When creating the session store, this doesn't work, because `getClient` doesn't return Promise but connect-mongo expects one:
```clientPromise: connection.getClient()```

Therefore, I have to do this:
```clientPromise: Promise.resolve(connection.getClient())```.

**Comment by mingchuno** [comment]
```js
{
  // Consider this block scope, `connection` is not promise in here and show does `client`
  const { connection } = await mongoose.connect(`mongodb://mongo:${dbPort}/${dbName}`, {
       useUnifiedTopology: true,
       useNewUrlParser: true,
       useCreateIndex: true
  });
  const client = connection.getClient()
}
// if this block scope is inside an async function and what you get will be a promise
```

**Comment by adamhavel** [comment]
I'm not sure I understand what you are getting at. This is the official example:
```
const clientP = mongoose.connect(
  'mongodb://root:example@127.0.0.1:27017',
  { useNewUrlParser: true, useUnifiedTopology: true }
).then(m => m.connection.getClient())
```

The only reason the `clientP` is Promise, is because it's returned by the `then` function which wraps its return value in `Promise.resolve`. Because I'm not using Promises this way, but employ `await` instead, I don't get a Promise.

My point: `clientPromise` should internally wrap the given value with `Promise.resolve` and not make the user conform to one specific way of dealing with asynchrony.

**Comment by jackharrhy** [comment]
Is there an issue with `clientPromise` being `Promise<MongoClient> | MongoClient | undefined` instead of `Promise<MongoClient> | undefined`?

You can just as easily `await mongoose.connect(...` as you can `mongoose.connect(...).then(` it, therefore removing the need to ever be handling a `Promise` to a connection.

Because of `clientPromise` expecting a promise, I'll have to go the same route as @adamhavel and wrap it in a `Promise.resolve`.

**Comment by mingchuno** [comment]
Created 4.3.0 release: https://github.com/jdesboeufs/connect-mongo/blob/master/CHANGELOG.md#430---2021-03-08
