### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by Vaibhav121121** [jdesboeufs/connect-mongo#408]
- **I'm submitting a ...**
  [x] bug report

- **Summary**
I just tried to use this package by copy pasting code from documentation and got error.

- **Other information** 
- The stacktrace for the error is 
store: MongoStore.create({ mongoUrl: process.env.MONGO_URI }),
                      ^
TypeError: Cannot read property 'create' of undefined
    at Object.<anonymous> (E:\Study\Sem. 6\Major Project\Online Food Ordering System\app.js:28:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

The code where I am getting error is -
` 
app.use(session({

    secret: "something",
    resave: false,
    saveUninitialized: false,
    store: MongoStore.create({ mongoUrl: process.env.MONGO_URI }), //this is line 28 where I am getting error
    cookie: { maxAge: 180 * 60 * 1000, secure: true }
}));
`

**Comment by mingchuno** [comment]
Which version you are using? and you are using typescript or javascript?

**Comment by Vaibhav121121** [comment]
I am using nodeJS 14.15.5, connect-mongo version 4.4.0 and express-session version 1.17.1

**Comment by dcatanzaro** [comment]
Change the

const MongoStore = require('connect-mongo').default;

to 

const MongoStore = require('connect-mongo');

**Comment by Calpert** [comment]
> Change the
> 
> const MongoStore = require('connect-mongo').default;
> 
> to
> 
> const MongoStore = require('connect-mongo');

My group is having this issue on our project. When I delete .default, I no longer get the error and am able to connect to the server. A couple of others, however, get that same error when they delete .default. Anyone know why?

**Comment by mingchuno** [comment]
It's interesting. Please check the version you are using. What version 4.4.0 does is remove the need for `require('connect-mongo').default` in javascript project. I have tested 4.4.0 with both JS and TS and the import / require work as expected. The related commit is in here https://github.com/jdesboeufs/connect-mongo/commit/f18dae083aec690f4f9a8f81283c99cf994b0558

**Comment by Vaibhav121121** [comment]
> Change the
> 
> const MongoStore = require('connect-mongo').default;
> 
> to
> 
> const MongoStore = require('connect-mongo');

Removing this solved my error. But I am confused in most of the tutorial I see people using 
`const MongoStore = require('connect-mongo')(session);`
which gives error now, error-
const MongoStore = require('connect-mongo')(session);
                                           ^
TypeError: Class constructor MongoStore cannot be invoked without 'new'
    at Object.<anonymous> (E:\Study\Sem. 6\Major Project\Online Food Ordering System\app.js:10:44)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by Vaibhav121121** [comment]
> Change the
> 
> const MongoStore = require('connect-mongo').default;
> 
> to
> 
> const MongoStore = require('connect-mongo');

This solved my problem, thanks.
