### ISSUE TITLE
Update MongoDB dependency and unpin it

### ISSUE THREAD

**Issue by rafw87** [jdesboeufs/connect-mongo#409]
Hi,
Fix in MongoDB regarding circular dependency mentioned in #386 is now published in [3.6.5](https://github.com/mongodb/node-mongodb-native/releases/tag/v3.6.5), so I think there is no longer reason to pin it to 3.6.3.
I checked in our project (we're using `connect-mongo` and also mongodb client for other things) and warning is not showing anymore, but currently I have duplicated mongodb 3.6.3 and 3.6.5, so would be nice to unpin it and allow latest versions.

Thanks 🙂

**Comment by mingchuno** [comment]
fixed in https://github.com/jdesboeufs/connect-mongo/commit/ddc131aeb221b1eac802afc67a7fd51beb854490
