### ISSUE TITLE
ERROR: TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by lingyun-z** [jdesboeufs/connect-mongo#412]
- **I'm submitting a ...**
  [x] bug report

- **Summary**
connect-mongo version: 4.4.1
I import connect-mongo package in my project which is the same as the usage in README.
Here is the error message ```TypeError: Cannot read property 'create' of undefined```.
```
import MongoStore from 'connect-mongo';

const options = {
  mongoUrl: envVars.DB_HOST,
  ttl: envVars.SESSION_TTL,
};

const sessionStore = MongoStore.create(options);
```
Here is the compiled js file.
```
const connect_mongo_1 = require("connect-mongo");
const options = {
    mongoUrl: envVars_1.envVars.DB_HOST,
    ttl: envVars_1.envVars.SESSION_TTL,
};
const sessionStore = connect_mongo_1.default.create(options);
```
Here is my ```tsconfig.json``` file.
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["es6", "esnext", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "noImplicitReturns": false,
    "outDir": "dist",
    "typeRoots": ["node_modules/@types"],
  },
  "files": ["src/main.ts"],
  "exclude": ["node_modules"]
}
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
I tried to remove ```.default``` in the js file, it can work. So I think the version of my typescript may not correct.
```
const connect_mongo_1 = require("connect-mongo");
const options = {
    mongoUrl: envVars_1.envVars.DB_HOST,
    ttl: envVars_1.envVars.SESSION_TTL,
};
const sessionStore = connect_mongo_1.create(options);
exports.default = sessionStore;
```

**Comment by mingchuno** [comment]
What version of the lib you are using? Make sure you are using latest version

**Comment by lingyun-z** [comment]
> What version of the lib you are using? Make sure you are using latest version

My connect-mongo version is 4.4.1.

**Comment by mingchuno** [comment]
Try to add `esModuleInterop: true`? Example of compiled JS file.

<img width="659" alt="Screenshot 2021-03-25 at 12 07 38 AM" src="https://user-images.githubusercontent.com/5472190/112343461-1eb9b180-8cfe-11eb-96a1-3cf797784242.png">

**Comment by lingyun-z** [comment]
Thanks for your help. It works, but affect lots of other packages' import way.
