### ISSUE TITLE
Must use express-session ?

### ISSUE THREAD

**Issue by ErnestBrandi** [jdesboeufs/connect-mongo#415]
- **I'm submitting a** question about how to use this project.

- **Summary**
Hi, is it mandatory to use `express-session` in the new version (v4) ?
I get the following error at build time : `Error: Cannot find module 'express-session'`.
With the v3 I was using `next-session` as session manager and it worked fine.

**Comment by mingchuno** [comment]
@ErnestBrandi Can you provide more code snippet on how you use `next-session`? Let see if we can migrate it to use V4. On the other hand, depends on your use case. I think there is chance that you can use may use `connect-mongo` directly w/o `next-session`? 🤔  Current V4 does not depend on the session impl as long as it matches the interface. So in theory you should be able to use another session impl.

**Comment by schamberg97** [comment]
Probably @ErnestBrandi doesn’t have express-session and thus he gets an error from [this](https://github.com/jdesboeufs/connect-mongo/blob/94b65f67d0190d17586a90068da45c0c81edc90a/src/lib/MongoStore.ts#L3)

**Comment by ErnestBrandi** [comment]
Hi, thanks for replying.
The `next-session` author says that the package won't receive future PR and recommend using `express-session` anyway (which I ended up doing).

**Comment by mingchuno** [comment]
So is your problem solve? I have take a look at `next-session`. What you need show be able to accomplish by `express-session` + `connect-mongo`. More code but you have more control over what you are doing.

**Comment by ErnestBrandi** [comment]
Yes it is solved, but not using `next-session`. Still, what about the import mentioned by @schamberg97 ? Doesn't it mean one must use `express-session` with `connect-mongo` or not ?

**Comment by mingchuno** [comment]
@ErnestBrandi Not really. Take a look at my `package.json`, `express-session` is just a dev dependency. Any "session" with same interface with `express-session` should work too. Take a look on my example:

```js
const session = require('express-session');
const MongoStore = require('connect-mongo');

app.use(session({
  secret: 'foo',
  store: MongoStore.create(options)
}));
```

I don't need `express-session` to create `MongoStore`. After all, `MongoStore` just expose [these functions](https://github.com/expressjs/session#session-store-implementation)

**Comment by ErnestBrandi** [comment]
Ok, thanks for clarifications :) I will close this issue.
