### ISSUE TITLE
collection.deleteMany() being called in a deprecated way, yielding a mongoDB Driver warning

### ISSUE THREAD

**Issue by hillct** [jdesboeufs/connect-mongo#422]
- **I'm submitting a ...**
  [X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- When used with a modern MongoDB driver (version 3.6.8 in this case but newer as well) we see this deprecation warning:
-  [MONGODB DRIVER] Warning: Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
    at emitWarning (node_modules/mongodb/lib/utils.js:851:17)

- The fault lies with top level use of w and j parameters in a deprecated way here: https://github.com/jdesboeufs/connect-mongo/blob/6ba9af7978b5a745a501ab7faf55d1d563d876c9/src/lib/MongoStore.ts#L235-L239

- theoretically, there may be a way to introduce writeConcern via a constructor parameter passed into options.writeOperationOptions but I haven't been successful with that theoretical workaround so far, and it would just be a workaround anyway. The superior solution would be to call collection.deleteMany() in a non-deprecated way.
- A review of he documentation https://docs.mongodb.com/manual/reference/write-concern/ suggests that seting the j parameter to true, would resolve the issue but I'm not sure which would be the optimal behavior for the particular session management goals of connect-mongo, nor am I a typeScript king of guy, so I leave it to the experts to determine the optimal parameter values here.

**Comment by mingchuno** [comment]
Thanks for your information. Related issue in here: https://github.com/strongloop/loopback-connector-mongodb/issues/616
I will take a look to see if any change is required since it is a deprecation warning only. Don't want to upgrade and break the others

**Comment by mingchuno** [comment]
Somehow we need to wait for this PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53636

Ref link for future me: http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#deleteMany

**Comment by borfig** [comment]
@mingchuno no more waiting - PR has been merged.

**Comment by hillct** [comment]
hanks for getting hid fix in place. Because there isn't a new NPM package featuring this fix, I attempted to use it via the Git repo, but was stymied by a few issues including circular dependencies and unit test errors. I was able to address he dependencies and one type error as reported by eslint (part of he test stack) but was stymied by the unit est failures. Please refer to https://github.com/jdesboeufs/connect-mongo/issues/428 for details

**Comment by mingchuno** [comment]
@hillct @borfig Please help take a look on the PR
https://github.com/jdesboeufs/connect-mongo/pull/430

**Comment by mingchuno** [comment]
v4.5.0 has been release, please try out @hillct
