### ISSUE TITLE
Error with ES6

### ISSUE THREAD

**Issue by yousuf4you** [jdesboeufs/connect-mongo#423]
When I tried to use ES6 it throws this error.
My input:
![type1](https://user-images.githubusercontent.com/60110696/121881774-80a01b00-cd31-11eb-923e-f8160aa20724.png)
![type](https://user-images.githubusercontent.com/60110696/121881789-85fd6580-cd31-11eb-9794-6d09cbdeb2df.png)

My Errors:
![error](https://user-images.githubusercontent.com/60110696/121881805-8d247380-cd31-11eb-9aea-f54eaf8b3aa5.png)

What is the error?

**Comment by mingchuno** [comment]
@yousuf4you What version you are using? https://github.com/jdesboeufs/connect-mongo/blob/master/MIGRATION_V4.md
Use `mongoUrl` instead of `url`

**Comment by yousuf4you** [comment]
I am using the version...
![errors2](https://user-images.githubusercontent.com/60110696/121989203-82afbb80-cdbd-11eb-934c-564a65287159.png)

**Comment by mingchuno** [comment]
Use `mongoUrl` instead of `url`
