### ISSUE TITLE
[Question] How does `autoRemove: 'native'` work?

### ISSUE THREAD

**Issue by Hawmex** [jdesboeufs/connect-mongo#425]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
How does `autoRemove: 'native'` work? I'm using Passport and I'm wondering how much time after a user logs out, their session is deleted from my mongoDB? Does it even work this way?
- **Other information**
none

**Comment by mingchuno** [comment]
@Hawmex As you can see from the source code. It use the MongoDB native TTL index to expire items base on `expires` field. And the field itself is base on the `ttl` set in the option.
https://github.com/jdesboeufs/connect-mongo/blob/master/src/lib/MongoStore.ts#L226

**Comment by Hawmex** [comment]
@mingchuno Ah, you mean the session is automatically deleted by MongoDB when the date specified in its `expires` field has come?

**Comment by schamberg97** [comment]
> @mingchuno Ah, you mean the session is automatically deleted by MongoDB when the date specified in its `expires` field has come?

Yes. Here’s the explanation: https://docs.mongodb.com/manual/core/index-ttl/

Take note that there may be a small delay before MongoDB manages to delete outdated session, depending on database load

**Comment by Hawmex** [comment]
Thanks @schamberg97. It got cleared up to me.
