### ISSUE TITLE
mongodb update

### ISSUE THREAD

**Issue by brettz9** [jdesboeufs/connect-mongo#426]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

With mongodb 4.0 being released, I'm wondering if you might be looking to update it. (I personally just don't want to have to use two copies, one with direct use of `mongodb` and one with `connect-mongo`.)

Thanks!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by mingchuno** [comment]
Need to take a look if any breaking change that will affect the existing user and also there is a reason to pin the driver version. Need to see if the issue resolve. https://github.com/jdesboeufs/connect-mongo/commit/37e8d3200e1ac37ad35b0ea2c39e51abb67974b4#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by guyellis** [comment]
[Here's the Changelog for MongoDB Driver 4.0.0](https://github.com/mongodb/node-mongodb-native/blob/4.0/docs/CHANGES_4.0.0.md)

**Comment by guyellis** [comment]
Also remember to remove [@types/mongodb](https://github.com/jdesboeufs/connect-mongo/blob/cceec185f2dd374e345e2f9417a185119828c4b5/package.json#L71) when experimenting with this because the mongodb 4.x dependency has built in types, which are different to the types in DefinitelyTyped.

**Comment by mingchuno** [comment]
@guyellis @brettz9 Please help take a look on the PR
https://github.com/jdesboeufs/connect-mongo/pull/430

**Comment by guyellis** [comment]
Apologies for only getting to this now. Thanks for doing this @mingchuno

**Comment by mingchuno** [comment]
v4.5.0 has been release, please try out @guyellis

**Comment by guyellis** [comment]
It works well. Thanks for doing this @mingchuno - much apprecaited!
