### ISSUE TITLE
MIGRATION_V4

### ISSUE THREAD

**Issue by guyellis** [jdesboeufs/connect-mongo#427]
During the migration to v4 I discovered that in the `session` collection that the `session` property was a string of JSON data in v3 but in v4 it is a JS object.

I had to blow away the `session` collection as part of my migration.

Not sure if that was something that I did wrong during the migration? If not, then perhaps that or notes to that effect should be added to the MIGRATION_V4.md doc?

**Comment by mingchuno** [comment]
Take a look on the `serialize`, `unserialize` and `serialize` options?

**Comment by guyellis** [comment]
I did't changed those options during the upgrade from v3 to v4. Did the default change for them?

**Comment by mingchuno** [comment]
@guyellis The default for option `stringify` should be `true` even in V4. Did you set it to false? 
https://github.com/jdesboeufs/connect-mongo/blob/cceec185f2dd374e345e2f9417a185119828c4b5/src/lib/MongoStore.ts#L145

**Comment by guyellis** [comment]
@mingchuno yes - that's exactly what I did - and I don't know why I did that. My apologies for taking up your time with this and thank you for clarifying and solving this.
