### ISSUE TITLE
Package file install and unit test issues

### ISSUE THREAD

**Issue by hillct** [jdesboeufs/connect-mongo#428]
- **I'm submitting a ...**
  [ X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Circular dependencies in package.json make this module un-installable from the git repository. The most current npm of version 4.4.1 was built before this issue arose, so is no impacted.
A fix for the circular dependencies can be found here: https://github.com/hillct/connect-mongo/tree/fixinstall
Not submitted as a pull request because it doesn't compltely fix the test failures which seem related to the unit test server yielding an internal server error. See below.
- **Other information** 
- test:unit yields he following:
- `Sun, 15 Aug 2021 15:55:32 GMT express-session deprecated undefined resave option; provide resave option at build/main/test/integration.spec.js:2:1198
Sun, 15 Aug 2021 15:55:32 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at build/main/test/integration.spec.js:2:1198
  test › integration.ts › simple case

  Difference:

  - Error {
  -   message: 'expected 200 "OK", got 500 "Internal Server Error"',
  - }
  + null

  › Test.<anonymous> (build/main/test/integration.spec.js:2:2674)
  › Test.assert (node_modules/supertest/lib/test.js:217:6)
  › Server.localAssert (node_modules/supertest/lib/test.js:167:12)

  lib › MongoStore.ts › before hook

  Rejected promise returned by test. Reason:

  MongoServerSelectionError {
    reason: TopologyDescription {
      commonWireVersion: null,
      compatibilityError: null,
      compatible: true,
      heartbeatFrequencyMS: 10000,
      localThresholdMS: 15,
      logicalSessionTimeoutMinutes: null,
      maxElectionId: null,
      maxSetVersion: null,
      servers: Map {
        '127.0.0.1:27017' => ServerDescription { … },
      },
      setName: null,
      stale: false,
      type: 'Single',
    },
    message: 'connect ECONNREFUSED 127.0.0.1:27017',
  }
`
As I'm not familiar with this test stack, I'm not able to offer much further insight.

**Comment by mingchuno** [comment]
@hillct Could you provide more details on the circular dependencies issue and why the fix work?

**Comment by mingchuno** [comment]
v4.5.0 has been release, please try out
