### ISSUE TITLE
 error TS2724: '"mongodb"' has no exported member named 'CommonOptions'. Did you mean 'CommandOptions'

### ISSUE THREAD

**Issue by mozgbrasil** [jdesboeufs/connect-mongo#429]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Good morning my friends

I opened the following question that mentions something related to your library if I could help in advance thank you

https://github.com/microsoft/TypeScript-Node-Starter/issues/340

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by mingchuno** [comment]
Yes, the microsoft repo didn't update the dependency and `connect-mongo` have quite a number of breaking change from v3 to v4. If you need to use, you have to migrate the code on your own.
