### ISSUE TITLE
ConnectMongoOption field `client` doesn't work with mongoose in TypeScript

### ISSUE THREAD

**Issue by riflowth** [jdesboeufs/connect-mongo#433]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I have tried to get client connection from opening connection by call `mongoose.connection.getClient()` to use on `client` field of `ConnectMongoOptions` but my vscode give me an error.

```ts
import MongoStore from 'connect-mongo';
import mongoose from 'mongoose';

MongoStore.create({
  client: mongoose.connection.getClient(),
  collectionName: 'sessions',
  ttl: 14 * 24 * 60 * 60,
  autoRemove: 'native'
});
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

My vscode show this error
```ts
Type 'MongoClient' is missing the following properties from type 
'MongoClient': options, serverApi, autoEncrypter, readConcern, and 3 more.
```

**Comment by pararell** [comment]
There is a problem with type Promise<MongoClient> for the clientPromise, it is in the same code as example in typescript:
https://github.com/jdesboeufs/connect-mongo/blob/master/example/mongoose.js
 It would be useful to add all examples to typescript, that should prevent these issues. 
Now here I have to use any to prevent the issue:
```
  const clientP: any = mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
  }).then(m => m.connection.getClient());
```

**Comment by huineng** [comment]
i got the above working since a long time without any issue. But today mongoose release v 6.0.0 and now i have an incompatibility issue

```
store: MongoStore.create({
            client: mongoose.connection.getClient(),
            stringify: false,
}),
```

```
Type 'import("/node_modules/mongoose/node_modules/mongodb/mongodb").MongoClient' is not 
assignable to type 'import("/node_modules/mongodb/mongodb").MongoClient'.
  The types of 'options.autoEncrypter' are incompatible between these types.
    Type 'import("/node_modules/mongoose/node_modules/mongodb/mongodb").AutoEncrypter | undefined' is 
not assignable to type 'import("/node_modules/mongodb/mongodb").AutoEncrypter | undefined'.ts(2322)
MongoStore.d.ts(15, 5): The expected type comes from property 'client' which is declared here 
on type 'ConnectMongoOptions'
(property) client?: MongoClient | undefined
```

and i'm not sure if these needs to be solved by mongoose or by connect-mongo

i'm ignoring it for now as i did not see any differences and all still works 
```
store: MongoStore.create({
            // @ts-ignore TS2322
            client: mongoose.connection.getClient(),
            stringify: false,
        }),
```

**Comment by huineng** [comment]
Is it possible to update mongodb to 4.1.1. there are differences between the 2 packages https://github.com/mongodb/node-mongodb-native/releases/tag/v4.1.1. thanks

**Comment by mingchuno** [comment]
Hi guys. Sorry for the late reply. Does moving `mongodb` to `peerDependency` help solve the issue?
Link to #434

**Comment by mingchuno** [comment]
4.6.0 released

**Comment by MaxMansfield** [comment]
@mingchuno I'm still seeing this issue with MongoDB set as a peerDep. I removed and reinstalled npm packages too.

    "mongoose": "^6.2.3"
    
     "mongodb": "^4.4.1"
     
Any thoughts?
