### ISSUE TITLE
The types of 'options.autoEncrypter' are incompatible

### ISSUE THREAD

**Issue by guyellis** [jdesboeufs/connect-mongo#434]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

When upgrading the mongodb dependency from `4.1.0` to `4.1.1` this is the TypeScript error:

```
Type 'import(".../node_modules/mongodb/mongodb").MongoClient' is 
not assignable to type 
'import(".../node_modules/connect-mongo/node_modules/mongodb/mongodb").MongoClient'.
  The types of 'options.autoEncrypter' are incompatible between these types.
    Type 'import(".../node_modules/mongodb/mongodb").AutoEncrypter |
     undefined' is not assignable to type 
     'import(".../node_modules/connect-mongo/node_modules/mongodb/mongodb").AutoEncrypter |
      undefined'.
```

I think that the fix is as simple as upgrading the dependency in package.json: https://github.com/jdesboeufs/connect-mongo/blob/3e273764c2b88da072a1eb2394ae70b5af158623/package.json#L62

**Comment by mingchuno** [comment]
link to #433 
I think I would tried the `peerDependency` approach first to see if it work. @rfox12 @guyellis Any idea on the drawback on moving `mongodb` to `peerDependency`? Will it break current user?

**Comment by mingchuno** [comment]
4.6.0 released

**Comment by rfox12** [comment]
I don't think we're going to break anyone's usage.  I upgraded just now and my update moved me to `mongodb@4.1.2` and `connect-mongo@4.6.0` with no issues!  Thanks

**Comment by guyellis** [comment]
> Any idea on the drawback on moving `mongodb` to `peerDependency`? Will it break current user?

I think it works the way that you've done it with `^` optimistic.

**Comment by huineng** [comment]
it works, i just had to delete node_modules and package-lock.json and reinstall. thanks

**Comment by guyellis** [comment]
> it works, i just had to delete node_modules and package-lock.json and reinstall. thanks

@huineng did you run into: `TextEncoder is not defined` that caused you to do that?

**Comment by huineng** [comment]
no sorry, i got "cannot find mongo"

**Comment by rfox12** [comment]
@huineng You'll simply want to ensure `mongodb` is in your package.json dependencies.
