### ISSUE TITLE
"Callback was already called" bug

### ISSUE THREAD

**Issue by ctaschereau** [jdesboeufs/connect-mongo#437]
At this line in the set function, we can see that the callback is in fact inside the _try_ statement. This has the side effect that if some code throws immediately after calling the set function, we will fall inside the catch statement of the set function and then have an "Callback was already called" error.

https://github.com/jdesboeufs/connect-mongo/blob/3e273764c2b88da072a1eb2394ae70b5af158623/src/lib/MongoStore.ts#L399-L404

example code : 
```
session.save(() => {
    throw new Error('some random error happened... (ex : uncaught)');
});
```

I have tested just moving the "callback" outside of the try/catch statement (and adding a return after the callback that is inside the catch) and the behaviour appears to be correct. I'll try and find the time to submit a proper pull request this weekend.

**Comment by mingchuno** [comment]
4.6.0 released
