### ISSUE TITLE
Fixed issue with the new Mongoose 6 API not returning a MongoClient-Promise anymore

### ISSUE THREAD

**Issue by moritzlaube** [jdesboeufs/connect-mongo#442]
I am submitting a solved issue to help out others who have a similar issue.

In my Node app I am using `Mongoose 6` with `express-session` and `connect-mongo`. 

I just upgraded to `Mongoose 6` and I've had some issues passing the `MongoClient`(I want to use an existing connection to the database) to the `clientPromise` option of the `MongoStore.create()` function.

With the new Mongoose API `connect-mongo` kept on complaining that `.then is not a function`. It seems the `getClient` function on the `mongoose.connection` doesn't return a promise anymore.

Here is my fix: 

```
/* CONNECT TO MONGODB */
mongoose.connect(process.env.MONGODB_CONNECTION_STRING)

/* FIX: CREATE A PROMISE FOR THE RETURNED MONGOCLIENT */
clientPromise = new Promise(function (resolve, reject) {
  resolve(mongoose.connection.getClient())
  reject(new Error('MongoClient Error'))
})

/* ... */

/* THEN USE IT TO CONNECT TO SESSION STORE */
app.use(
  session({
    secret: process.env.SESSION_SECRET,
    store: MongoStore.create({
      clientPromise,
    }),
  })
)

**Comment by JonasHavers** [comment]
Thanks for sharing, @moritzlaube !

You can also use the `client` option in `ConnectMongoOptions`:
```
const sessionStore = MongoStore.create({
  client: mongoose.connection.getClient(),
});
```

If you want to use the `clientPromise` option for whatever reason (e.g. promises chaining), there is also a new `asPromise()` function in Mongoose's `Connection` ([docs](https://mongoosejs.com/docs/api/connection.html#connection_Connection-asPromise)) that returns "a promise that resolves when this connection successfully connects to MongoDB":
```
const clientPromise = mongoose.connection.asPromise().then((connection) => connection.getClient());
```

Or use a shorter version of @moritzlaube 's solution:
```
const clientPromise = Promise.resolve(mongoose.connection.getClient());
```
