### ISSUE TITLE
How to delete all of a user's sessions?

### ISSUE THREAD

**Issue by oneguyhacking** [jdesboeufs/connect-mongo#447]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ X] question about how to use this project

- **Summary**
When I delete a user from my system, I'd like to delete all their sessions as well.  I have seen your answer to this question from 2016 (#201), which is to refer to req.sessionStore.db to issue a remove command, but it seems that this is no longer set:

```
debug> exec req.sessionStore.db
undefined
```

What is the correct way to do this now?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I declare the session parser as:
```
const sessionDB = `mongodb://${mongo_user}:${mongo_pwd}@localhost:4005`;
const MongoStore = require('connect-mongo');

global.sessionParser = session({
    secret: '<key>',
    saveUninitialized: false,  
    resave: false,   
    cookie: {
        path: '/',
        httpOnly: true,
        secure: true,  
        maxAge: null,
    },

     store: MongoStore.create({
        mongoUrl: sessionDB,
        dbName: 'Web-Sessions',
        ttl: 30 * 24 * 60 * 60,
        autoRemove: "native",	
        stringify: false,	
    }),
});
app.use(sessionParser);
```

**Comment by bradenmitchell** [comment]
Any progress on this?

**Comment by mingchuno** [comment]
It is more an `express-session` question. https://www.npmjs.com/package/express-session
Can you try `req.session.destroy()` ?

**Comment by mingchuno** [comment]
Then I think it is outside the scope of `express-session`. You should manually find and delete the session using mongodb driver directly.
