### ISSUE TITLE
Does not using "mongooseConnection" cause any issues with mongoose?

### ISSUE THREAD

**Issue by skeddles** [jdesboeufs/connect-mongo#464]
- **I'm submitting a ...**
  [ ] question about how to use this project

- **Summary**
I'm updating my project from v2 to v4, following the guide here: https://github.com/jdesboeufs/connect-mongo/blob/master/MIGRATION_V4.md

My project was using the deprecated `mongooseConnection` option. I tried to use the `.getClient()` method, but couldn't figure that out, so instead opted for the first option which was just supplying the `mongoUrl` option instead, which I'm also using in `mongoose.connect()`. After updating this, my site seems to be working normally.

My question is there any downside to this? Will it cause any issues with mongoose? 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by gkostov** [comment]
> is there any downside to this?

You will end up with one more connection to Mongo so should be using a little more memory. How much of an issue that is only depends on your environment.

> Will it cause any issues with mongoose?

No. It's a separate connection so Mongoose shall not be affected.

Cheers

**Comment by skeddles** [comment]
thanks!
