### ISSUE TITLE
Error in documentation for passing client promises.

### ISSUE THREAD

**Issue by andrewfrankcare** [jdesboeufs/connect-mongo#467]
- **I'm submitting a ...**
  [* ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Thanks for the project! I believe the example code might have a bug in it when passing a client promise to MongoStore.create():

```
// Database name present in the connection string will be used
app.use(session({
  store: MongoStore.create({ clientPromise })
}));

// Explicitly specifying database name
app.use(session({
  store: MongoStore.create({
    clientPromise,
    dbName: 'test-app'
  })
}));
```

Should that be ```clientPromise: clientPromise``` in the above two places? Thanks.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by mingchuno** [comment]
Why should it be?

**Comment by andrewfrankcare** [comment]
It does not appear to be valid JS to me or my compiler. Perhaps I'm missing something, e.g.

Fails:

```
let object = {"hello"};
                     ^
SyntaxError: Unexpected token '}'
```

Works:

```
let object = {clientPromise: "hello"};
```

**Comment by mingchuno** [comment]
This is JS feature, object shorthand : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

```js
const a = 1
const obj = { a }
```

**Comment by andrewfrankcare** [comment]
Thanks, I didn't know about that feature! I think it would be better including the key explicitly, but I agree the docs are correct.
