### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by VarunGuptaPy** [jdesboeufs/connect-mongo#483]
# Deprecation Warning: `punycode` module usage in `connect-mongo`

## Issue Description

I'm encountering a deprecation warning related to the use of the `punycode` module when using the `connect-mongo` package. The warning message is as follows:

(node:77064) [DEP0040] DeprecationWarning: The` punycode` module is deprecated. Please use a userland alternative instead.

## Dependency Tree

The `punycode` module is being used indirectly through the dependency chain of `connect-mongo`. Here is the relevant portion of the dependency tree:

![Screenshot 2024-06-17 at 12 08 50 PM](https://github.com/jdesboeufs/connect-mongo/assets/86191471/82a9b00f-4bd0-4532-9881-1cf08925d80a)

## Steps to Reproduce

1. Install `connect-mongo` in an Express project.
2. Run the project and observe the deprecation warning in the console.

## Expected Behavior

No deprecation warnings should be present, and the `punycode` module should be replaced with a suitable userland alternative.

## Environment

- Node.js version: 21.7.1
- `connect-mongo` version: 5.1.0
- Operating System: [your operating system]

## Suggested Solution

Investigate the possibility of updating the dependencies or using alternative packages that do not rely on the deprecated `punycode` module.

## Additional Information

This issue affects the stability and future compatibility of projects using `connect-mongo`, as reliance on deprecated modules may lead to unexpected behavior or security vulnerabilities.

Thank you for your attention to this matter. If any additional information is required, please let me know.

**Comment by eviltik** [comment]
@jdesboeufs please ...

**Comment by jdesboeufs** [comment]
I will look at this.

**Comment by jdesboeufs** [comment]
`mongodb` is not a direct dependency but a peer dependency.
You need `mongodb` to deal with a MongoDB database, this library is built upon on it.

The issue has already been reported to MongoDB: https://jira.mongodb.org/browse/NODE-5709
You can safely use `mongodb >= 6.3.0` which remove the deprecation notice.

Thank you for reporting this :)
