### ISSUE TITLE
Why connect-mongo creates new session for every request?

### ISSUE THREAD

**Issue by msmirnov** [jdesboeufs/connect-mongo#57]
I have two nodejs servers (web-server, socket-server), that are connected to each other by socket.io. On web-service I use express.js and passport.js as authentication middleware.

This is my web-server config:

``` javascript
var express = require('express'),
    mongo = require('mongodb'),
    io = require('socket.io'),
    passport = require('passport'),
    LocalStrategy = require('passport-local').Strategy,
    MongoStore = require('connect-mongo')(express);
```

``` javascript
app.configure(function () {
    app.use(express.cookieParser());
    app.use(express.methodOverride());
    app.use(express.bodyParser());
    app.use(express.session({
        secret: 'keyboard cat',
        store: new MongoStore({
          db: 'MyDatabase'
        })
    }));
    app.use(passport.initialize());
    app.use(passport.session());
    app.use(app.router);
    app.use(express.static(__dirname + '/htdocs'));
});
```

When I use connect-mongo, it creates a new session for each http-request:
(0 element creates with log in request, other elements are created, when I press F5).
![mongovue](https://f.cloud.github.com/assets/2646531/235861/891d08a0-87c7-11e2-8fe7-2e20e2e2d24c.PNG)

When web-server takes socket connection, connect-mongo creates new session. There are about 50 new documents per minute.

What could be the reason?

In the case of updating the page, helped tip to add app.use(express.favicon()).

With sockets question is still actual.

My socket-server code

``` javascript
function sendPortalJSON (portal_id, data, _event) {
    https.get({
        host : ...,
        port : ...,
        path : "/" + _event + "?data=" + encodeURIComponent( JSON.stringify (data))
    }).on('error', function (err) {

    });
}
...
sendPortalJSON(1, agent_data[i].d, "cpu-details");
```

And on web-server:

``` javascript
app.get('/cpu-details', function (req, res) {});
```

**Comment by Unitech** [comment]
YaY (dirty) solution found!

https://github.com/wesleytodd/express-session-passport-cleanup

https://github.com/jaredhanson/passport/issues/279#issuecomment-69839937

**Comment by Chokidar39** [comment]
Answer? It’s right here https://stackdev.space/questions/sailsjs-security-measures-for-managing-socket-requests
